import { useState, useMemo } from "react";

// ============================================================
// FULL DATABASE
// ============================================================
const DATABASE = {
  cats: {
    "High Protein": {
      Kibble: [
        { brand: "PRIMAL NUGGETS", pct: "57%", product: "Rabbit Recipe" },
        { brand: "PRIMAL NUGGETS", pct: "57%", product: "Turkey Recipe" },
        { brand: "PRIMAL NUGGETS", pct: "53%", product: "Pork Formula" },
        { brand: "PRIMAL NUGGETS", pct: "47%", product: "Chicken & Salmon Recipe" },
        { brand: "PRIMAL NUGGETS", pct: "36%", product: "Freeze Dried Raw Toppers Turkey Recipe" },
        { brand: "OPEN FARM", pct: "47%", product: "Harvest Chicken Recipe" },
        { brand: "OPEN FARM", pct: "47%", product: "Chicken & Salmon Recipe" },
        { brand: "OPEN FARM", pct: "41%", product: "Wild-Caught + Salmon & Cod Recipe" },
        { brand: "SMACK", pct: "50%", product: "Pacific Fish Feast Recipe" },
        { brand: "SMACK", pct: "45%", product: "Very Berry for Cats Recipe" },
        { brand: "SMACK", pct: "40%", product: "Purrfect Pork Recipe" },
        { brand: "FELINE NATURAL", pct: "48%", product: "Chicken & Lamb Feast" },
        { brand: "FELINE NATURAL", pct: "47%", product: "Beef & Hoki Feast" },
        { brand: "FELINE NATURAL", pct: "45%", product: "Lamb & King Salmon Feast" },
        { brand: "THE HONEST KITCHEN", pct: "35%", product: "Chicken & Fish Recipe" },
        { brand: "THE HONEST KITCHEN", pct: "35%", product: "Chicken Recipe" },
        { brand: "GO! SOLUTIONS", pct: "46%", product: "Carnivore Chicken, Turkey + Duck Recipe" },
        { brand: "GO! SOLUTIONS", pct: "42%", product: "Carnivore Salmon + Cod Recipe" },
        { brand: "ACANA", pct: "38%", product: "Kitten" },
        { brand: "ACANA", pct: "38%", product: "Indoor Cat" },
        { brand: "ACANA", pct: "37%", product: "First Feast" },
        { brand: "ACANA", pct: "37%", product: "Grasslands" },
        { brand: "ACANA", pct: "37%", product: "Indoor Entrée" },
        { brand: "ACANA", pct: "37%", product: "Pacifica" },
        { brand: "ACANA", pct: "37%", product: "Wild Prairie" },
        { brand: "ORIJEN", pct: "42%", product: "Fit & Trim" },
        { brand: "ORIJEN", pct: "40%", product: "Kitten" },
        { brand: "ORIJEN", pct: "40%", product: "Original" },
        { brand: "ORIJEN", pct: "40%", product: "Guardian 8" },
        { brand: "ORIJEN", pct: "40%", product: "Guardian 8 Senior" },
        { brand: "ORIJEN", pct: "40%", product: "Regional Red" },
        { brand: "ORIJEN", pct: "40%", product: "Six Fish" },
        { brand: "ULTRA", pct: "40%", product: "Original Kitten" },
        { brand: "ULTRA", pct: "40%", product: "Original" },
        { brand: "ULTRA", pct: "38%", product: "Farmstead Recipe" },
        { brand: "ULTRA", pct: "38%", product: "Ocean Recipe" },
        { brand: "TIKICAT BORN CARNIVORE", pct: "43%", product: "High Protein Deboned Chicken & EGG" },
        { brand: "TIKICAT BORN CARNIVORE", pct: "43%", product: "High Protein Chicken, Herring & Salmon" },
        { brand: "TIKICAT BORN CARNIVORE", pct: "42%", product: "High Protein Herring & Salmon" },
        { brand: "TIKICAT BORN CARNIVORE", pct: "38%", product: "Optimal Weight Turkey Recipe" },
        { brand: "FIRSTMATE", pct: "42%", product: "Pacific Ocean Fish Meal With Blueberries" },
        { brand: "FIRSTMATE", pct: "36%", product: "Chicken Meal With Blueberries Formula" },
        { brand: "FIRSTMATE", pct: "36%", product: "Cage-Free Duck Meal With Blueberries" },
        { brand: "FIRSTMATE", pct: "35%", product: "Indoor Cat Formula" },
        { brand: "STELLA & CHEWY'S", pct: "40%", product: "Raw Blend Turkey, Chicken & Duck" },
        { brand: "STELLA & CHEWY'S", pct: "38%", product: "Raw Coated Kibble Chicken Recipe" },
        { brand: "NATURAL BALANCE", pct: "35%", product: "Original Ultra Fat Cat" },
        { brand: "MERRICK", pct: "38%", product: "Real Chicken + Sweet Potato" },
        { brand: "OPEN FARM", pct: "40%", product: "Kitten Chicken & Turkey Recipe" },
        { brand: "OPEN FARM", pct: "37%", product: "Homestead Turkey & Chicken" },
        { brand: "OPEN FARM", pct: "37%", product: "Catch-Of-The-Season Whitefish" },
        { brand: "OPEN FARM", pct: "37%", product: "Wild-Caught Salmon Recipe" },
        { brand: "OPEN FARM", pct: "37%", product: "Pasture-Raised Lamb Recipe" },
        { brand: "SQUAREPET VFS", pct: "48%", product: "Powercat TRKY CHK" },
        { brand: "SQUAREPET VFS", pct: "44%", product: "Powercat HRNG SLM" },
        { brand: "ROYAL CANIN", pct: "36%", product: "Digestive" },
        { brand: "SCIENCE DIET", pct: "35.5%", product: "Perfect Weight Adult Chicken Recipe" },
        { brand: "PERFORMATRIN NATURALS", pct: "35%", product: "Chicken & Veggies Recipe" },
        { brand: "PROPLAN", pct: "40%", product: "Adult Sensitive Skin & Stomach Lamb & Rice" },
        { brand: "PROPLAN", pct: "36%", product: "Adult Indoor Hairball Salmon & Rice" },
        { brand: "PROPLAN", pct: "36%", product: "Live Clear Adult Chicken & Rice" },
        { brand: "PROPLAN", pct: "36%", product: "Complete Essentials Chicken & Rice" },
        { brand: "PURINA ONE", pct: "37%", product: "Indoor Advantage With Real Turkey" },
        { brand: "TASTE OF THE WILD", pct: "42%", product: "Rocky Mountain With Roasted Venison & Smoke-Flavored Salmon" },
        { brand: "BLUE WILDERNESS", pct: "40%", product: "Kitten With Chicken" },
        { brand: "BLUE WILDERNESS", pct: "40%", product: "Adult With Chicken" },
        { brand: "BLUE WILDERNESS", pct: "40%", product: "Adult With Salmon" },
        { brand: "BLUE TASTEFULS", pct: "38%", product: "Adult Indoor With Chicken" },
        { brand: "BLUE TASTEFULS", pct: "36%", product: "Adult Weight Control With Chicken" },
        { brand: "BLUE TASTEFULS", pct: "36%", product: "Kitten Chicken & Brown Rice Recipe" },
      ],
      Cans: [
        { brand: "TIKICAT", pct: "17%", product: "AHI TUNA & MACKEREL Recipe" },
        { brand: "TIKICAT", pct: "16%", product: "Succulent Chicken Recipe" },
        { brand: "TIKICAT", pct: "16%", product: "Tuna & Crab Surimi Recipe" },
        { brand: "TIKICAT", pct: "16%", product: "AHI TUNA & CHICKEN Recipe" },
        { brand: "TIKICAT ALOHA FRIENDS", pct: "16%", product: "AHI TUNA & PRAWNS Recipe In Broth" },
        { brand: "TIKICAT ALOHA FRIENDS", pct: "16%", product: "AHI TUNA RECIPE" },
        { brand: "TIKICAT BABY", pct: "15%", product: "Wild Salmon Recipe" },
        { brand: "TIKICAT BABY", pct: "15%", product: "Wild Salmon & Chicken Recipe" },
        { brand: "TIKICAT BABY", pct: "15%", product: "Chicken & Salmon Recipe" },
        { brand: "TIKICAT BABY", pct: "15%", product: "Chicken & EGG Recipe" },
        { brand: "TIKICAT", pct: "13%", product: "Sardine Cutlets Recipe in Sardine Consomme" },
        { brand: "TIKICAT", pct: "11%", product: "Sardine Cutlets Recipe in Lobster Consomme" },
        { brand: "TIKICAT", pct: "11%", product: "Mackerel & Sardines Recipe" },
        { brand: "TIKICAT", pct: "11%", product: "Tuna & Pumpkin Recipe" },
        { brand: "TIKICAT", pct: "11%", product: "Tuna, Shrimp & Pumpkin Recipe in Broth" },
        { brand: "LOVIBLES", pct: "12%", product: "Simply Irresistible" },
        { brand: "LOVIBLES", pct: "12%", product: "Furrever & Always" },
        { brand: "LOVIBLES", pct: "11%", product: "My One & Only" },
        { brand: "LOVIBLES", pct: "11%", product: "Key to My Heart" },
        { brand: "LOVIBLES", pct: "11%", product: "Over the Moo-n" },
        { brand: "LOVIBLES", pct: "11%", product: "Seashore Love" },
        { brand: "FANCY FEAST", pct: "14%", product: "Tuna Feast Flaked" },
        { brand: "FANCY FEAST", pct: "14%", product: "Shredded White Meat Chicken Fare" },
        { brand: "FANCY FEAST", pct: "12%", product: "Seafood Feast PATE" },
        { brand: "FANCY FEAST", pct: "12%", product: "Ocean Whitefish & Tuna Feast PATE" },
        { brand: "FANCY FEAST", pct: "12%", product: "Cod, Sole & Shrimp Feast PATE" },
        { brand: "FANCY FEAST", pct: "11%", product: "Salmon Feast PATE" },
        { brand: "FANCY FEAST", pct: "11%", product: "White Meat Chicken Florentine" },
        { brand: "FANCY FEAST", pct: "11%", product: "Tuna Florentine With Spinach" },
        { brand: "FANCY FEAST", pct: "11%", product: "Wild Salmon Florentine With Spinach" },
        { brand: "FANCY FEAST", pct: "11%", product: "Salmon Feast In Gravy Grilled" },
        { brand: "FANCY FEAST", pct: "11%", product: "Tuna Feast In Gravy Grilled" },
        { brand: "FANCY FEAST", pct: "11%", product: "Turkey Feast In Gravy Grilled" },
        { brand: "FANCY FEAST", pct: "11%", product: "Turkey & Giblets Feast PATE" },
        { brand: "FANCY FEAST", pct: "11%", product: "Beef Flavour Feast PATE" },
        { brand: "WHISKAS", pct: "12%", product: "Salmon" },
        { brand: "WHISKAS", pct: "11%", product: "Beef Entrée" },
        { brand: "WHISKAS", pct: "11%", product: "Chicken & Liver Entrée" },
        { brand: "WHISKAS", pct: "11%", product: "Chicken Entrée" },
        { brand: "ORIJEN", pct: "14%", product: "Tuna & Beef Entrée" },
        { brand: "ORIJEN", pct: "12%", product: "Regional Red Entrée" },
        { brand: "ORIJEN", pct: "12%", product: "Chicken & Salmon Entrée" },
        { brand: "ORIJEN", pct: "12%", product: "Original Entrée" },
        { brand: "ORIJEN", pct: "11%", product: "Duck & Chicken Entrée" },
        { brand: "ULTRA", pct: "11%", product: "Tuna Bisque Kitten To Adult" },
        { brand: "ULTRA", pct: "11%", product: "Trout Bisque Kitten To Adult" },
        { brand: "ACANA", pct: "11%", product: "Chunks In Broth Chicken & Salmon Recipe" },
        { brand: "WELLNESS", pct: "11%", product: "Whitefish & Tuna Entrée" },
        { brand: "WELLNESS", pct: "11%", product: "Chicken Entrée" },
        { brand: "WELLNESS", pct: "11%", product: "Chicken & Herring Dinner" },
        { brand: "SNAPPY TOM", pct: "16%", product: "Tuna With Whitebait and Crabmeat" },
        { brand: "SNAPPY TOM", pct: "15%", product: "Tuna Temptations" },
        { brand: "OPEN FARM", pct: "12%", product: "Arctic Char" },
        { brand: "OPEN FARM", pct: "12%", product: "Salmon & Cod" },
        { brand: "PRIME", pct: "11%", product: "Chicken Formula PATE" },
        { brand: "PRIME", pct: "11%", product: "Whitefish Formula PATE" },
        { brand: "FIRSTMATE", pct: "11%", product: "Wild Salmon & Wild Tuna Formula" },
        { brand: "FIRSTMATE", pct: "11%", product: "Wild Pacific Salmon Formula" },
        { brand: "FIRSTMATE", pct: "11%", product: "Wild Tuna Formula PATE" },
      ],
      Treats: [
        { brand: "PURE BITES", pct: "80%", product: "Wild-Caught Tuna" },
        { brand: "PURE BITES", pct: "78%", product: "Wild-Caught Shrimp" },
        { brand: "PURE BITES", pct: "74%", product: "Freeze-Dried Chicken Breast" },
        { brand: "PURE BITES", pct: "74%", product: "Wild-Caught Minnow" },
        { brand: "PURE BITES", pct: "72%", product: "Chicken & Duck Liver" },
        { brand: "PURE BITES", pct: "62%", product: "Wild-Caught Salmon" },
        { brand: "PERFORMATRIN ULTRA", pct: "75%", product: "Freeze-Dried Turkey" },
        { brand: "PERFORMATRIN ULTRA", pct: "62%", product: "Freeze-Dried Raw Chicken Liver" },
        { brand: "THIS & THAT FELINE", pct: "79.3%", product: "Chicken" },
        { brand: "THIS & THAT FELINE", pct: "79.2%", product: "Crack Nip Tuna" },
        { brand: "THIS & THAT FELINE", pct: "77.6%", product: "Crack Nip Salmon" },
        { brand: "WILD VIBES", pct: "79%", product: "Kangaroo & Bone Broth" },
        { brand: "WILD VIBES", pct: "78%", product: "Chicken Hearts & Bone Broth" },
        { brand: "WILD VIBES", pct: "68%", product: "Sun-Dried Sardines" },
        { brand: "WILD VIBES", pct: "66%", product: "Beef Liver & Bone Broth" },
        { brand: "ORIJEN", pct: "55%", product: "Six Fish" },
        { brand: "CRUMPS' NATURALS", pct: "55%", product: "Beef Freeze-Dried Cat Treats" },
        { brand: "WILD PACIFIC", pct: "74%", product: "Dried Gourmet Fish" },
        { brand: "WILD PACIFIC", pct: "74%", product: "Whiting Bites Dried Gourmet Fish" },
        { brand: "WILD PACIFIC", pct: "65%", product: "Herring Steaks Dried Gourmet Fish" },
        { brand: "PRIMAL LIVER.LAUGH.LOVE", pct: "60%", product: "Freeze-Dried Pork" },
        { brand: "SURF KITTY KITTY", pct: "61%", product: "White Fish Krill Coated" },
      ],
    },
    "High Fat": {
      Kibble: [
        { brand: "OPEN FARM (FREEZE-DRIED)", pct: "40%", product: "Harvest Chicken Recipe" },
        { brand: "OPEN FARM (FREEZE-DRIED)", pct: "37%", product: "Chicken & Salmon Recipe" },
        { brand: "OPEN FARM (FREEZE-DRIED)", pct: "25%", product: "Wild-Caught Salmon & Cod Recipe" },
        { brand: "SMACK (RAW DEHYDRATED)", pct: "32%", product: "Pacific Fish Feast Recipe" },
        { brand: "SMACK (RAW DEHYDRATED)", pct: "30%", product: "Purrfect Pork Recipe" },
        { brand: "SMACK (RAW DEHYDRATED)", pct: "25%", product: "Very Berry For Cats Recipe" },
        { brand: "FELINE NATURALS (FREEZE-DRIED)", pct: "36%", product: "Lamb & King Salmon Feast" },
        { brand: "FELINE NATURALS (FREEZE-DRIED)", pct: "34%", product: "Beef & Hoki Feast" },
        { brand: "FELINE NATURALS (FREEZE-DRIED)", pct: "31%", product: "Chicken & Lamb Feast" },
        { brand: "PRIMAL NUGGETS", pct: "32%", product: "Chicken & Salmon Recipe" },
        { brand: "PRIMAL NUGGETS", pct: "21%", product: "Rabbit Recipe" },
        { brand: "GO SOLUTIONS", pct: "20%", product: "Skin & Coat Care Chicken Recipe with Grains" },
        { brand: "ORIJEN", pct: "20%", product: "Regional Red" },
        { brand: "ORIJEN", pct: "20%", product: "Kitten" },
        { brand: "ORIJEN", pct: "20%", product: "Original" },
        { brand: "ROYAL CANIN", pct: "23%", product: "Mother & Baby Cat (1-4 Months)" },
        { brand: "ROYAL CANIN", pct: "20%", product: "Sensitive Digestion" },
        { brand: "SCIENCE DIET", pct: "21%", product: "Sensitive Stomach & Skin Kitten" },
        { brand: "SQUARE PET", pct: "20%", product: "PWRCT HRNG SLM" },
        { brand: "OVEN BAKED TRADITION", pct: "20%", product: "Dental Care Chicken Formula" },
        { brand: "BLUE WILDERNESS", pct: "20%", product: "Kitten Chicken And Antioxidant-Rich" },
        { brand: "BLUE TASTEFULS", pct: "20%", product: "Kitten Chicken & Brown Rice" },
        { brand: "PRIME", pct: "21%", product: "Kitten Chicken & Rice Formula" },
      ],
      Cans: [
        { brand: "BLUE WILDERNESS", pct: "9%", product: "Salmon Recipe" },
        { brand: "BLUE WILDERNESS", pct: "8%", product: "Chicken Recipe" },
        { brand: "BLUE TASTEFULS", pct: "7%", product: "Salmon Recipe For Kitten" },
        { brand: "BLUE TASTEFULS", pct: "8%", product: "Chicken Entrée" },
        { brand: "BLUE TASTEFULS", pct: "8%", product: "Turkey & Chicken Entrée" },
        { brand: "BLUE TASTEFULS", pct: "7%", product: "Salmon Entrée PATE" },
        { brand: "WELLNESS", pct: "8%", product: "Chicken Entrée Smooth Loaf" },
        { brand: "WELLNESS", pct: "7%", product: "Beef & Salmon Entrée" },
        { brand: "WELLNESS", pct: "7%", product: "Turkey Dinner Smooth Loaf" },
        { brand: "WELLNESS", pct: "7%", product: "Chicken & Lobster Dinner" },
        { brand: "WELLNESS", pct: "7%", product: "Beef & Chicken Dinner" },
        { brand: "THE HONEST KITCHEN", pct: "8.5%", product: "Chicken Recipe" },
        { brand: "THE HONEST KITCHEN", pct: "7.5%", product: "Beef & Chicken" },
        { brand: "PURINA PROPLAN", pct: "7%", product: "Sensitive Skin & Stomach Chicken Entrée" },
        { brand: "PRIME", pct: "8.5%", product: "Kitten Chicken Formula PATE" },
        { brand: "PRIME", pct: "8%", product: "Adult Chicken Formula PATE" },
        { brand: "PRIME", pct: "7.5%", product: "Turkey Formula PATE" },
        { brand: "PRIME", pct: "7%", product: "Beef Formula PATE" },
        { brand: "BOREAL", pct: "8%", product: "Cobb Chicken & Heritage Turkey Formula" },
        { brand: "BOREAL", pct: "7.5%", product: "Pork & Trout Formula" },
        { brand: "BOREAL", pct: "7.5%", product: "Cobb Chicken, NZ Lamb, Angus Beef" },
        { brand: "BOREAL", pct: "7%", product: "Cobb Chicken & Canadian Duck Formula" },
        { brand: "FIRSTMATE", pct: "8%", product: "Turkey Formula" },
        { brand: "FIRSTMATE", pct: "8%", product: "Pork & Apple Formula" },
        { brand: "FIRSTMATE", pct: "7%", product: "Turkey & Wild Tuna Formula" },
        { brand: "OPEN FARM", pct: "8%", product: "Salmon" },
        { brand: "OPEN FARM", pct: "8%", product: "Arctic Char" },
        { brand: "OPEN FARM", pct: "8%", product: "Chicken & Salmon Recipe" },
        { brand: "OPEN FARM", pct: "7.5%", product: "Harvest Chicken Recipe" },
        { brand: "OPEN FARM", pct: "7.5%", product: "Homestead Turkey Recipe" },
        { brand: "OPEN FARM", pct: "7%", product: "Wild-Caught Salmon Recipe" },
        { brand: "OPEN FARM", pct: "7%", product: "Chicken & Grass-Fed Beef Recipe" },
        { brand: "ULTRA", pct: "8%", product: "Turkey PATE" },
        { brand: "ULTRA", pct: "8%", product: "Turkey, Salmon & Duck PATE" },
        { brand: "ULTRA", pct: "7%", product: "Chicken PATE Kitten To Adult" },
        { brand: "ULTRA", pct: "7%", product: "Chicken PATE Kitten" },
        { brand: "ULTRA", pct: "7%", product: "Salmon Bisque" },
        { brand: "ORIJEN", pct: "7%", product: "Chicken & Salmon Entrée" },
        { brand: "ACANA", pct: "7%", product: "Beef Recipe" },
        { brand: "ACANA", pct: "7%", product: "Chicken & Tuna Recipe" },
        { brand: "ACANA", pct: "7%", product: "Lamb Recipe" },
      ],
      Treats: [
        { brand: "VITAL ESSENTIAL", pct: "21%", product: "Duck Liver" },
        { brand: "VITAL ESSENTIAL", pct: "20%", product: "Chicken Hearts" },
        { brand: "VITAL ESSENTIAL", pct: "19%", product: "Ahi Tuna Bites" },
        { brand: "ORIJEN", pct: "40%", product: "Regional Red" },
        { brand: "ORIJEN", pct: "35%", product: "Original" },
        { brand: "ORIJEN", pct: "35%", product: "Tundra" },
        { brand: "ALL TEMPTATIONS", pct: "21%", product: "All Temptations" },
        { brand: "BLUE BURSTS", pct: "21%", product: "With Paw Lickin' Chicken" },
        { brand: "BLUE BURSTS", pct: "19%", product: "With Savory Seafood" },
        { brand: "CRUMPS' NATURALS", pct: "27%", product: "Chicken" },
        { brand: "FELINE GREENIES", pct: "19%", product: "Chicken Flavor Healthy Indoor" },
        { brand: "FELINE GREENIES", pct: "19%", product: "Tuna Flavor" },
        { brand: "PURE BITES", pct: "32%", product: "Skin & Coat Formula" },
        { brand: "PURE BITES", pct: "22%", product: "Gut & Digestion Formula" },
        { brand: "WILD VIBES", pct: "16%", product: "Chicken Heart & Bone Broth" },
        { brand: "SURF KITTY KITTY", pct: "16%", product: "White Fish Krill Coated" },
        { brand: "ULTRA", pct: "29%", product: "White Fish" },
        { brand: "ULTRA", pct: "16%", product: "Salmon Recipe" },
      ],
    },
    "High Fiber": {
      Kibble: [
        { brand: "SCIENCE DIET", pct: "11%", product: "Indoor Chicken Recipe" },
        { brand: "SCIENCE DIET", pct: "10.5%", product: "Oral Care Chicken & Brown Rice" },
        { brand: "ROYAL CANIN", pct: "11.2%", product: "Care Weight" },
        { brand: "ROYAL CANIN", pct: "10.8%", product: "Care Appetite Control" },
        { brand: "ROYAL CANIN", pct: "8.5%", product: "Care Hairball" },
        { brand: "NATURAL BALANCE", pct: "9%", product: "FAT CATS Chicken Meal & Salmon Meal" },
        { brand: "PERFORMATRIN PRIME", pct: "9%", product: "Healthy Weight Chicken & Rice Formula" },
        { brand: "PERFORMATRIN PRIME", pct: "9%", product: "Oral Care Chicken & Rice Formula" },
        { brand: "PERFORMATRIN PRIME", pct: "8%", product: "Hairball Chicken & Rice" },
        { brand: "PERFORMATRIN PRIME", pct: "7%", product: "Indoor Chicken & Rice Formula" },
        { brand: "TIKICAT", pct: "10%", product: "Optimal Weight Turkey Recipe" },
        { brand: "GO! SOLUTIONS", pct: "10%", product: "Weight Management + Joint Care" },
        { brand: "GO! SOLUTIONS", pct: "10%", product: "G.F. Salmon Recipe" },
        { brand: "GO! SOLUTIONS", pct: "9%", product: "Hairball Control + Urinary Care Chicken Recipe with Grains" },
        { brand: "IAMS", pct: "8.3%", product: "Indoor Weight & Hairball Care with Chicken & Turkey" },
        { brand: "BLUE BUFFALO", pct: "8%", product: "Weight Control Adult With Chicken" },
        { brand: "BOREAL FUNCTIONAL", pct: "7%", product: "G.F. Chicken Formula" },
      ],
      Cans: [
        { brand: "SCIENCE DIET", pct: "3.5%", product: "Perfect Weight Roasted Vegetable & Chicken" },
        { brand: "SCIENCE DIET", pct: "3%", product: "Sensitive Stomach & Skin Chicken & Beef" },
        { brand: "SCIENCE DIET", pct: "3%", product: "Tender Tuna Dinner Adult 7+" },
        { brand: "SCIENCE DIET", pct: "3%", product: "Chicken & Spinach Casserole Adult 1-6" },
        { brand: "SCIENCE DIET", pct: "3%", product: "Sensitive Stomach & Skin Salmon & Tuna" },
        { brand: "SCIENCE DIET", pct: "2.5%", product: "Savory Turkey Entrée Adult 1-6" },
        { brand: "SCIENCE DIET", pct: "2%", product: "Hairball Control Savory Chicken Entrée" },
        { brand: "SCIENCE DIET", pct: "2%", product: "Healthy Cuisine Tender Chicken & Rice" },
        { brand: "SCIENCE DIET", pct: "2%", product: "Healthy Cuisine Roasted Chicken & Rice" },
        { brand: "SCIENCE DIET", pct: "2%", product: "Sensitive Stomach & Skin Salmon & Vegetable" },
        { brand: "PERFORMATRIN PRIME", pct: "2.5%", product: "Digestion Support Turkey Formula Stew" },
        { brand: "PERFORMATRIN PRIME", pct: "2.5%", product: "Indoor Salmon Formula PATE" },
        { brand: "ROYAL CANIN", pct: "3%", product: "Weight Thin Slices In Gravy" },
        { brand: "ROYAL CANIN", pct: "3%", product: "Weight Loaf In Sauce" },
        { brand: "ROYAL CANIN", pct: "2.9%", product: "Hair & Skin Chunks In Gravy" },
        { brand: "ROYAL CANIN", pct: "2.8%", product: "Instinctive Chunks In Gravy" },
        { brand: "ROYAL CANIN", pct: "2.7%", product: "Digestive Loaf In Sauce" },
        { brand: "ROYAL CANIN", pct: "2.7%", product: "Hair & Skin Thin Slices In Gravy" },
        { brand: "ROYAL CANIN", pct: "2.7%", product: "Digestive Chunks In Gravy" },
        { brand: "ROYAL CANIN", pct: "2.5%", product: "Digestive Thin Slices In Gravy" },
        { brand: "BLUE TRUE SOLUTIONS", pct: "3%", product: "Digestive Care" },
        { brand: "BLUE TRUE SOLUTIONS", pct: "3%", product: "Weight Care" },
        { brand: "BLUE TASTEFULS", pct: "2%", product: "Chicken Entrée PATE" },
        { brand: "BLUE TASTEFULS", pct: "2%", product: "Chicken Recipe" },
        { brand: "PURINA PROPLAN", pct: "2.6%", product: "Vital Systems Chicken Entrée" },
        { brand: "PURINA PROPLAN", pct: "2.6%", product: "Vital Systems Tuna Entrée" },
        { brand: "TIKICAT", pct: "2%", product: "BABY Chicken & Salmon Kittens" },
        { brand: "TIKICAT", pct: "2%", product: "BABY Chicken & EGG Recipe Kitten" },
        { brand: "OPEN FARM", pct: "2%", product: "Harvest Chicken Rustic Blend" },
        { brand: "OPEN FARM", pct: "2%", product: "Harvest Turkey Rustic Blend" },
        { brand: "OPEN FARM", pct: "2%", product: "Herring & Mackerel Rustic Blend" },
        { brand: "OPEN FARM", pct: "2%", product: "Wild-Caught Salmon Rustic Blend" },
        { brand: "OPEN FARM", pct: "2%", product: "Arctic Char" },
        { brand: "OPEN FARM", pct: "2%", product: "Salmon & Cod" },
        { brand: "OPEN FARM", pct: "2%", product: "Salmon" },
        { brand: "ULTRA", pct: "2%", product: "Chicken PATE Senior" },
      ],
      Treats: [
        { brand: "FELINE GREENIES", pct: "10%", product: "Savory Salmon Flavor" },
        { brand: "FELINE GREENIES", pct: "10%", product: "Catnip Flavor" },
        { brand: "FELINE GREENIES", pct: "10%", product: "Oven-Roasted Chicken Flavor" },
        { brand: "FELINE GREENIES", pct: "6.5%", product: "Healthy Indoor Tuna Flavor" },
        { brand: "FELINE GREENIES", pct: "6.5%", product: "Healthy Indoor Chicken Flavor" },
        { brand: "CRUMPS' NATURALS", pct: "7%", product: "Beef" },
        { brand: "PUREBITES", pct: "6%", product: "Gut & Digestion" },
        { brand: "WILDLY NATURAL", pct: "8%", product: "Chicken Flavor" },
        { brand: "WILDLY NATURAL", pct: "8%", product: "Salmon Flavor" },
        { brand: "WILDLY NATURAL", pct: "8%", product: "Tuna Flavor" },
        { brand: "WELLNESS WHIMZEES", pct: "7%", product: "Natural Dental Treat Chicken Flavor" },
        { brand: "WELLNESS WHIMZEES", pct: "7%", product: "Chicken & Tuna Flavor" },
        { brand: "WELLNESS WHIMZEES", pct: "6%", product: "Chicken & Salmon Flavor" },
      ],
    },
    "Low Protein": {
      Kibble: [
        { brand: "ROYAL CANIN", pct: "27%", product: "Indoor 7+ years" },
        { brand: "ROYAL CANIN", pct: "27%", product: "Indoor Adult" },
        { brand: "SCIENCE DIET", pct: "27%", product: "Adult 7+" },
        { brand: "SCIENCE DIET", pct: "28%", product: "Adult 1-6 Salmon & Brown Rice" },
      ],
      Cans: [
        { brand: "SCIENCE DIET", pct: "4%", product: "Sensitive Stomach & Skin Kitten Salmon & Vegetable Stew" },
        { brand: "SCIENCE DIET", pct: "5%", product: "Perfect Digestion Adult 1-6 Salmon & Tuna Dinner" },
        { brand: "SCIENCE DIET", pct: "5%", product: "Sensitive Stomach & Skin Adult" },
        { brand: "SCIENCE DIET", pct: "5.5%", product: "Healthy Cuisine Roasted Chicken & Rice Medley" },
        { brand: "SCIENCE DIET", pct: "6%", product: "Sensitive Stomach & Skin Chicken & Beef Dinner" },
        { brand: "SCIENCE DIET", pct: "6.3%", product: "Sensitive Stomach & Skin Tuna & Vege." },
        { brand: "SCIENCE DIET", pct: "6.5%", product: "Chicken & Spinach Casserole Adult" },
        { brand: "SCIENCE DIET", pct: "6.5%", product: "Tender Chicken & Rice Medley Kitten" },
        { brand: "SCIENCE DIET", pct: "6.5%", product: "Perfect Weight Roasted Vegetable & Chicken Medley Adult" },
        { brand: "ROYAL CANIN", pct: "6.7%", product: "Hairball Care Thin Slices in Gravy" },
        { brand: "ULTRA", pct: "6.5%", product: "Tuna & Tilapia Recipe In Gelee Adult" },
      ],
      Treats: [
        { brand: "INABA CHURU", pct: "5.5%", product: "Salmon Recipe" },
        { brand: "INABA CHURU", pct: "5.5%", product: "Salmon With Tuna Recipe" },
        { brand: "INABA CHURU", pct: "7%", product: "Tuna Recipe" },
        { brand: "INABA CHURU", pct: "7%", product: "Skin & Coat Tuna Recipe" },
        { brand: "INABA CHURU", pct: "7%", product: "Senior 10+ years Chicken Recipe" },
        { brand: "INABA CHURU", pct: "7%", product: "Senior 10+ years Tuna Recipe" },
        { brand: "INABA CHURU", pct: "7%", product: "Chicken Recipe" },
        { brand: "INABA CHURU", pct: "7%", product: "Hairball Control Tuna Recipe" },
        { brand: "INABA CHURU", pct: "7%", product: "Skin & Coat Chicken Recipe" },
        { brand: "INABA CHURU", pct: "7%", product: "Hairball Control Chicken Recipe" },
        { brand: "INABA CHURU", pct: "7%", product: "Tuna With Scallop Recipe" },
        { brand: "INABA CHURU", pct: "7%", product: "Chicken With Scallop Recipe" },
        { brand: "INABA CHURU", pct: "7%", product: "Tuna Recipe" },
        { brand: "INABA CHURU", pct: "7%", product: "Chicken with Cheese Recipe" },
        { brand: "PERFORMATRIN PRIME", pct: "7%", product: "Urinary Care Chicken Formula" },
        { brand: "PERFORMATRIN PRIME", pct: "7%", product: "Skin & Coat Care Salmon Formula" },
        { brand: "PERFORMATRIN PRIME", pct: "7%", product: "Hairball Control Tuna Formula" },
        { brand: "PERFORMATRIN PRIME", pct: "7%", product: "Healthy Weight Snapper Formula" },
        { brand: "ULTRA", pct: "7%", product: "Tuna Variety" },
        { brand: "ULTRA", pct: "7%", product: "Chicken Variety" },
        { brand: "ULTRA", pct: "7%", product: "Tuna & Pumpkin Recipe" },
        { brand: "ULTRA", pct: "7%", product: "Tuna & Salmon Recipe" },
        { brand: "ULTRA", pct: "7%", product: "Chicken & Shrimp Recipe" },
        { brand: "ULTRA", pct: "7%", product: "Chicken Recipe" },
        { brand: "ULTRA", pct: "7%", product: "Tuna & Scallop Recipe" },
        { brand: "ULTRA", pct: "8%", product: "Lickable & Salmon Recipe" },
        { brand: "ULTRA", pct: "8%", product: "Chicken & Scallop Recipe" },
        { brand: "TIKICAT STIX", pct: "8%", product: "Serving With Salmon in Creamy Gravy" },
        { brand: "TIKICAT STIX", pct: "9%", product: "Easy-to-Eat Lickable With Chicken in Creamy Gravy" },
        { brand: "PUREBITES", pct: "11%", product: "Chicken Breast Mixer. Treat" },
        { brand: "PUREBITES", pct: "11%", product: "Wild Tuna Mixer. Treat" },
        { brand: "PETGREENS", pct: "11%", product: "Salmon Recipe" },
        { brand: "PETGREENS", pct: "11%", product: "Turkey & Duck Recipe" },
        { brand: "PETGREENS", pct: "11%", product: "Chicken Recipe" },
        { brand: "PETGREENS", pct: "14%", product: "Tuna Recipe" },
      ],
    },
    "Low Fat": {
      Kibble: [
        { brand: "ROYAL CANIN", pct: "8.4%", product: "Indoor Weight" },
        { brand: "NATURAL BALANCE", pct: "9.5%", product: "Ultra Fat Cats Chicken Meal & Salmon" },
        { brand: "SCIENCE DIET", pct: "9%", product: "Perfect Weight Adult Chicken Recipe" },
        { brand: "PURINA PRIME", pct: "10%", product: "Healthy Weight Chicken & Rice Formula" },
        { brand: "PURINA PROPLAN", pct: "10%", product: "Indoor Hairball Salmon & Rice Formula" },
        { brand: "PURINA PROPLAN", pct: "10%", product: "Indoor Hairball Turkey & Rice Formula" },
        { brand: "TASTEFULS", pct: "10%", product: "Adult Cat Weight Control Chicken & Brown Rice" },
        { brand: "ULTRA", pct: "10%", product: "Healthy Weight Recipe With Salmon" },
        { brand: "GO! SOLUTIONS", pct: "10%", product: "Weight Management + Joint Care G.F. Salmon Recipe" },
        { brand: "GO! SOLUTIONS", pct: "10%", product: "Weight Management + Joint Care G.F. Chicken Recipe" },
        { brand: "IAMS", pct: "11%", product: "Indoor Weight & Hairball Care Chicken & Turkey" },
      ],
      Cans: [
        { brand: "TIKICAT", pct: "0.05%", product: "Born Carnivore Broths With Chicken" },
        { brand: "TIKICAT", pct: "0.05%", product: "Born Carnivore Broths With Tuna" },
        { brand: "WERUVA CATS IN THE KITCHEN", pct: "1%", product: "The Karate Kitty Beef & Salmon Dinner in a Hydrating Puree" },
        { brand: "SNAPPY TOM LITES", pct: "1%", product: "Tuna with Salmon" },
        { brand: "SNAPPY TOM LITES", pct: "1%", product: "Tuna with Crabmeat" },
        { brand: "SNAPPY TOM LITES", pct: "1%", product: "Tuna with Cheese" },
        { brand: "SNAPPY TOM LITES", pct: "1%", product: "Tuna with Shrimp and Calamari" },
        { brand: "WERUVA", pct: "1.2%", product: "Grandma's Chicken Soup with Chicken & Pumpkin" },
        { brand: "WERUVA B.F.F.", pct: "1.4%", product: "Tuna & Chicken CHARM ME" },
        { brand: "WERUVA B.F.F.", pct: "1.4%", product: "Tuna & Salmon SWEET CHEEKS (Dinner In Gravy)" },
        { brand: "FANCY FEAST", pct: "1.5%", product: "Tuna Florentine with Spinach" },
        { brand: "FANCY FEAST", pct: "1.5%", product: "White Meat Chicken Florentine" },
        { brand: "FANCY FEAST", pct: "1.5%", product: "Wild Salmon Florentine" },
        { brand: "FANCY FEAST", pct: "2%", product: "Ocean White Fish & Tuna Feast" },
        { brand: "FANCY FEAST", pct: "2%", product: "Cod, Sole & Shrimp Feast" },
        { brand: "SCIENCE DIET", pct: "1.7%", product: "Sensitive Stomach & Skin (Kitten)" },
        { brand: "SCIENCE DIET", pct: "1.8%", product: "Perfect Digestion Adult Chkn, Veg, Rice" },
        { brand: "SCIENCE DIET", pct: "1.8%", product: "Perfect Weight Adult Roasted Veg, Ckn" },
        { brand: "SCIENCE DIET", pct: "2%", product: "Sensitive Stomach & Skin (Adult)" },
        { brand: "ROYAL CANIN", pct: "1.8%", product: "Digestive Loaf in Sauce" },
        { brand: "ROYAL CANIN", pct: "1.9%", product: "Adult Instinctive" },
        { brand: "PRIME", pct: "2%", product: "Healthy Weight White Fish Formula Pate" },
        { brand: "LOVIBLES", pct: "2%", product: "Furrever & Always" },
        { brand: "LOVIBLES", pct: "2%", product: "Simply Irresistible Cod, Sole & Shrimp" },
        { brand: "BLUE TRUE SOLUTIONS", pct: "2%", product: "Skin & Coat Care" },
        { brand: "ULTRA", pct: "2%", product: "Chicken & Duck Recipe In Broth" },
        { brand: "ULTRA", pct: "2%", product: "Tuna & Tilapia Recipe In Gelee" },
      ],
      Treats: [
        { brand: "PURE BITES MIXER.TREAT", pct: "0.2%", product: "Chicken Breast" },
        { brand: "PURE BITES MIXER.TREAT", pct: "0.2%", product: "Tuna & Salmon" },
        { brand: "PURE BITES MIXER.TREAT", pct: "0.2%", product: "Wild Tuna" },
        { brand: "PURE BITES MIXER.TREAT", pct: "2%", product: "Freeze Dried Wild Caught Shrimp" },
        { brand: "CHURU", pct: "0.2%", product: "Hairball Control Chicken Recipe" },
        { brand: "CHURU", pct: "0.2%", product: "Tuna With Scallop Recipe" },
        { brand: "CHURU", pct: "0.2%", product: "Chicken With Scallop Recipe" },
        { brand: "CHURU", pct: "0.2%", product: "Tuna Recipe" },
        { brand: "CHURU", pct: "0.2%", product: "Chicken With Cheese Recipe" },
        { brand: "CHURU", pct: "0.2%", product: "Chicken Recipe" },
        { brand: "CHURU", pct: "0.2%", product: "Hairball Control Tuna Recipe" },
        { brand: "INABA", pct: "0.8%", product: "Tuna Fillet Grilled Extra Tender In Tuna Flavored Broth" },
        { brand: "INABA", pct: "0.8%", product: "Chicken Fillet Grilled In Chicken Flavored Broth" },
        { brand: "INABA", pct: "0.8%", product: "Chicken Fillet Grilled In Scallop Flavored Broth" },
        { brand: "INABA", pct: "0.8%", product: "Tuna Fillet Grilled In Crab Flavored Broth" },
      ],
    },
    "Low Fiber": {
      Kibble: [
        { brand: "SMACK", pct: "1.5%", product: "Pacific Fish Feast" },
        { brand: "SMACK", pct: "1.8%", product: "Very Berry For Cats" },
        { brand: "SMACK", pct: "1.8%", product: "Purrfect Pork" },
        { brand: "GO! SOLUTIONS", pct: "1.5%", product: "Carnivore Chicken, Turkey & Duck" },
        { brand: "GO! SOLUTIONS", pct: "2.5%", product: "Skin & Coat Care Chicken Recipe" },
        { brand: "GO! SOLUTIONS", pct: "2.5%", product: "Carnivore Salmon & Cod Recipe" },
        { brand: "PRIMAL", pct: "3%", product: "Rabbit Recipe" },
        { brand: "PRIMAL", pct: "3%", product: "Turkey Recipe" },
        { brand: "PURINA PROPLAN", pct: "2%", product: "Live Clear Chicken & Rice Formula" },
        { brand: "PURINA PROPLAN", pct: "2%", product: "Complete Essentials Chicken & Rice Formula" },
        { brand: "PURINA PROPLAN", pct: "2%", product: "Urinary Tract Health System Chkn, Rice" },
        { brand: "PURINA PROPLAN", pct: "2.5%", product: "Sensitive Skin & Stomach Lamb & Rice" },
        { brand: "PERFORMATRIN PRIME", pct: "2%", product: "Kitten Chicken & Rice Formula" },
        { brand: "PERFORMATRIN PRIME", pct: "3%", product: "Adult Chicken & Rice Formula" },
        { brand: "PERFORMATRIN PRIME", pct: "3%", product: "Senior 7+ Chicken & Rice Formula" },
        { brand: "SCIENCE DIET", pct: "3%", product: "Sensitive Stomach & Skin Adult Chicken & Rice Recipe" },
        { brand: "MERRICK", pct: "2.5%", product: "Sensitive Stomach Real Chicken & Sweet Potato Recipe" },
        { brand: "MERRICK", pct: "3%", product: "Pasture-Raised Lamb Recipe" },
        { brand: "MERRICK", pct: "3%", product: "Kitten Chicken & Turkey" },
        { brand: "OPEN FARM", pct: "3%", product: "Homestead Turkey & Chicken Recipe" },
        { brand: "OPEN FARM", pct: "3%", product: "Catch-of-the-Season Whitefish Recipe" },
        { brand: "OPEN FARM", pct: "3%", product: "Wild-Caught Salmon Recipe" },
        { brand: "OPEN FARM", pct: "3%", product: "Taste Cats Crave (Good bowl)" },
        { brand: "OPEN FARM", pct: "3%", product: "Harvest Chicken & Brown Rice" },
        { brand: "OPEN FARM", pct: "3%", product: "Wild Caught Salmon & Brown Rice" },
        { brand: "ORIJEN", pct: "3%", product: "Kitten Fresh or Raw Chicken, Turkey & Wild Caught Fish" },
        { brand: "ORIJEN", pct: "3%", product: "Original Fresh Or Raw Chicken, Turkey & Wild-Caught Fish" },
        { brand: "ORIJEN", pct: "3%", product: "Guardian 8 Senior" },
        { brand: "ORIJEN", pct: "3%", product: "Wild-Caught Salmon, Duck & Chicken" },
        { brand: "ORIJEN", pct: "3%", product: "Regional Red" },
        { brand: "ORIJEN", pct: "3%", product: "Six Fish" },
        { brand: "ACANA", pct: "3%", product: "Wild Prairie" },
        { brand: "ACANA", pct: "3%", product: "Pacifica" },
        { brand: "ACANA", pct: "3%", product: "Grasslands" },
        { brand: "ACANA", pct: "3%", product: "Kitten Original Recipe" },
        { brand: "PERFORMATRIN ULTRA", pct: "3%", product: "Potato & Turkey Recipe" },
        { brand: "PERFORMATRIN ULTRA", pct: "3%", product: "Potato & Salmon Recipe" },
        { brand: "PERFORMATRIN ULTRA", pct: "3%", product: "Original Recipe" },
        { brand: "PERFORMATRIN ULTRA", pct: "3%", product: "Lamb & Brown Rice Recipe" },
        { brand: "PERFORMATRIN ULTRA", pct: "3%", product: "Chicken & Brown Rice Recipe" },
        { brand: "IAMS", pct: "3%", product: "Healthy Adult With Chicken" },
        { brand: "LOVIBLES", pct: "3%", product: "Kitten Farmer's Delight Chicken Flavor" },
        { brand: "LOVIBLES", pct: "3%", product: "Adult Farmer's Delight Chicken Flavor" },
        { brand: "LOVIBLES", pct: "3%", product: "Fisherman's Catch Seafood Flavor" },
        { brand: "TASTE OF THE WILD", pct: "3%", product: "Rocky Mountain Feline Recipe with Roasted Venison & Smoke-Flavored Salmon" },
        { brand: "PERFORMATRIN NATURALS", pct: "3%", product: "Chicken & Veggies Recipe Kitten" },
      ],
      Cans: [
        { brand: "TIKICAT", pct: "0%", product: "Wild Salmon Recipe in Salmon Consomme" },
        { brand: "TIKICAT", pct: "0%", product: "Succulent Chicken Recipe in Chicken Consomme" },
        { brand: "TIKICAT", pct: "0%", product: "Wild Salmon & Chicken Recipe in Chicken Consomme" },
        { brand: "TIKICAT AFTER DARK", pct: "0.6%", product: "Chicken & Lamb Recipe in Broth" },
        { brand: "WERUVA CATS IN KITCHEN", pct: "0.5%", product: "Mostly All Weruva Cats In Kitchen" },
        { brand: "B.F.F. ORIGINAL MINCED", pct: "0.2%", product: "All" },
        { brand: "WERUVA WX", pct: "1%", product: "All" },
        { brand: "WERUVA", pct: "1%", product: "Mideast Feast" },
        { brand: "WERUVA", pct: "1%", product: "Mack & Jack" },
        { brand: "WERUVA", pct: "1%", product: "Meow Luau" },
        { brand: "FIRSTMATE", pct: "0.2%", product: "Pork & Apple Formula" },
        { brand: "FIRSTMATE", pct: "0.4%", product: "Wild Pacific Salmon Formula" },
        { brand: "FIRSTMATE", pct: "0.4%", product: "Cage-Free Turkey Formula" },
        { brand: "FIRSTMATE", pct: "0.4%", product: "Wild Pacific Salmon Formula (Whipped Pate)" },
        { brand: "FIRSTMATE", pct: "0.4%", product: "Wild Salmon & Wild Tuna Formula" },
        { brand: "OPEN FARM", pct: "1%", product: "All" },
        { brand: "OPEN FARM", pct: "2%", product: "All Rustic Blends" },
        { brand: "OPEN FARM", pct: "2%", product: "Silky Mousse" },
        { brand: "MERRICK", pct: "1%", product: "Chicken Recipe" },
        { brand: "MERRICK", pct: "1%", product: "Tuna Recipe" },
        { brand: "WELLNESS", pct: "1%", product: "All" },
        { brand: "FANCY FEAST", pct: "0.5%", product: "Hors d'oeuvre" },
        { brand: "ORIJEN", pct: "0.5%", product: "All" },
        { brand: "ACANA", pct: "1%", product: "All" },
        { brand: "PURINA PROPLAN", pct: "0.2%", product: "Urinary Tract Health System Chicken Entrée" },
        { brand: "PURINA PROPLAN", pct: "0.5%", product: "Urinary Tract System Ocean White Fish" },
        { brand: "PURINA PROPLAN", pct: "0.5%", product: "Urinary Tract System Turkey & Giblets" },
        { brand: "PERFORMATRIN PRIME", pct: "1%", product: "Chicken Formula Pate Kitten" },
        { brand: "PERFORMATRIN PRIME", pct: "1%", product: "Turkey Formula Pate" },
        { brand: "PERFORMATRIN PRIME", pct: "1%", product: "Chicken Formula Pate Adult" },
        { brand: "PERFORMATRIN PRIME", pct: "1%", product: "Whitefish Formula Pate" },
        { brand: "PERFORMATRIN PRIME", pct: "1%", product: "Beef Formula Pate" },
        { brand: "PERFORMATRIN NATURALS", pct: "1%", product: "Tuna & Chicken Recipe Adult" },
        { brand: "PERFORMATRIN ULTRA", pct: "0.5%", product: "Salmon & Tuna Recipe Gelee" },
        { brand: "PERFORMATRIN ULTRA", pct: "1.5%", product: "Chicken Recipe in Gravy" },
        { brand: "PERFORMATRIN ULTRA", pct: "2%", product: "Senior Pate" },
      ],
      Treats: [
        { brand: "PRIME", pct: "0.1%", product: "Healthy Weight" },
        { brand: "PRIME", pct: "1%", product: "Skin & Coat" },
        { brand: "PRIME", pct: "1.5%", product: "Hairball Control" },
        { brand: "PRIME", pct: "1%", product: "Urinary Care" },
        { brand: "TIKICAT STIX", pct: "0.5%", product: "All" },
        { brand: "INABA CHURU", pct: "0.3%", product: "All" },
        { brand: "INABA JUICY BITES", pct: "0.5%", product: "All" },
        { brand: "INABA TUNA FILLET GRILLED", pct: "0.5%", product: "All" },
        { brand: "PERFORMATRIN ULTRA", pct: "0.1%", product: "Tuna & Scallop Recipe" },
        { brand: "PERFORMATRIN ULTRA", pct: "0.5%", product: "Tuna Recipe" },
        { brand: "PERFORMATRIN ULTRA", pct: "1%", product: "Chicken & Scallop Recipe" },
        { brand: "PURE BITES", pct: "0.2%", product: "Wild-Caught Tuna" },
        { brand: "PURE BITES", pct: "2%", product: "Wild-Caught Minnow" },
        { brand: "PRIMAL", pct: "1%", product: "The G.O.A.T. Liver Laugh Love" },
        { brand: "WILD PACIFIC", pct: "1%", product: "Herring Steaks" },
        { brand: "WILD PACIFIC", pct: "1%", product: "Whiting Bits" },
        { brand: "WILD PACIFIC", pct: "1%", product: "Salmon" },
      ],
    },
  },
  dogs: {
    "High Protein": {
      Kibble: [
        { brand: "VFS", pct: "40%", product: "RED Meat" },
        { brand: "VFS", pct: "40%", product: "TK & CK" },
        { brand: "ORIJEN", pct: "39%", product: "Small Breed" },
        { brand: "ORIJEN", pct: "38%", product: "Puppy" },
        { brand: "ORIJEN", pct: "38%", product: "Original" },
        { brand: "ORIJEN", pct: "38%", product: "Regional Red" },
        { brand: "ORIJEN", pct: "38%", product: "Six Fish" },
        { brand: "ORIJEN", pct: "38%", product: "Amazing Grains Puppy" },
        { brand: "ORIJEN", pct: "38%", product: "Amazing Grains Original" },
        { brand: "ORIJEN", pct: "38%", product: "Amazing Grains Regional Red" },
        { brand: "PURINA PROPLAN", pct: "30%", product: "Puppy under 1 Year (Chicken & Rice Formula)" },
        { brand: "PURINA ONE", pct: "30%", product: "With Blend of Real Turkey & Venison" },
        { brand: "BLUE WILDERNESS", pct: "36%", product: "Nature's Evolutionary Diet S.B. With Chicken" },
        { brand: "BLUE WILDERNESS", pct: "34%", product: "With Chicken Adult" },
        { brand: "RAWMIX", pct: "31%", product: "Open Prairie Recipe" },
        { brand: "RAWMIX", pct: "30%", product: "Front Range Recipe" },
        { brand: "RAWMIX", pct: "30%", product: "Tide & Terrain Recipe" },
        { brand: "RAWMIX", pct: "30%", product: "Wild Ocean Recipe" },
        { brand: "EPIC BLEND", pct: "30%", product: "Salmon & Super Food Recipe" },
        { brand: "EPIC BLEND", pct: "30%", product: "Beef & Super Food Recipe" },
        { brand: "EPIC BLEND", pct: "30%", product: "Chicken & Super Food Recipe" },
        { brand: "OPEN FARM", pct: "30%", product: "Ancient Stream" },
        { brand: "OPEN FARM", pct: "30%", product: "Puppy Salmon & Sweet Potato Recipe" },
        { brand: "OPEN FARM", pct: "30%", product: "Homestead Turkey & Chicken Recipe" },
        { brand: "OPEN FARM", pct: "30%", product: "BEEF Recipe" },
        { brand: "OPEN FARM", pct: "30%", product: "Pasture-Raised Lamb Recipe" },
        { brand: "OPEN FARM", pct: "30%", product: "Catch-of-the-Season Whitefish" },
        { brand: "MERRICK", pct: "32%", product: "Real Texas Beef & Sweet Potato Recipe" },
        { brand: "MERRICK", pct: "32%", product: "Real Chicken & Sweet Potato Recipe" },
        { brand: "ZIGNATURE", pct: "32%", product: "Turkey Formula" },
        { brand: "ZIGNATURE", pct: "31%", product: "Trout & Salmon Meal Formula" },
        { brand: "ZIGNATURE", pct: "30.5%", product: "Catfish Formula" },
        { brand: "ZIGNATURE", pct: "30%", product: "Pork Formula" },
        { brand: "ULTRA", pct: "37%", product: "Original Recipe" },
        { brand: "ULTRA", pct: "35%", product: "Hillside Recipe" },
        { brand: "ULTRA", pct: "34%", product: "Spring Valley Recipe" },
        { brand: "ULTRA", pct: "32%", product: "Autumn Ranch Recipe" },
        { brand: "ULTRA", pct: "32%", product: "Ocean Recipe and Prairie Recipe" },
        { brand: "ULTRA", pct: "32%", product: "Foothills Recipe" },
        { brand: "ULTRA", pct: "31%", product: "Foothills Recipe" },
        { brand: "FIRSTMATE", pct: "32%", product: "High Performance For Active Dogs & Puppies" },
        { brand: "GO! SOLUTIONS", pct: "36%", product: "Puppy Carnivore Chk, Trky + Duck" },
        { brand: "GO! SOLUTIONS", pct: "34%", product: "Adult Chk, Trky + Duck" },
        { brand: "GO! SOLUTIONS", pct: "32%", product: "Senior Chk, Trky + Duck" },
        { brand: "ACANA", pct: "35%", product: "Pacifica Recipe" },
        { brand: "ACANA", pct: "35%", product: "Grasslands Recipe" },
        { brand: "ACANA", pct: "35%", product: "Ranchlands Recipe" },
        { brand: "ACANA", pct: "35%", product: "Wild Prairie" },
        { brand: "ACANA", pct: "35%", product: "Light & Fit Recipe" },
        { brand: "ACANA", pct: "33%", product: "Senior Recipe" },
        { brand: "ACANA", pct: "33%", product: "Puppy Recipe" },
        { brand: "ACANA", pct: "31%", product: "Puppy Small Breed Recipe" },
        { brand: "ACANA", pct: "31%", product: "Adult Small Breed Recipe" },
        { brand: "ACANA", pct: "31%", product: "Healthy Grains Puppy Sea & Farm" },
        { brand: "ACANA", pct: "31%", product: "Healthy Grains Puppy" },
        { brand: "ACANA", pct: "31%", product: "Lamb with Apple" },
        { brand: "ACANA", pct: "31%", product: "Duck with Pea" },
        { brand: "ACANA", pct: "31%", product: "Pork with Squash" },
        { brand: "STELLA & CHEWY'S", pct: "36%", product: "Raw Coated Kibble Cage-Free Puppy Chicken Recipe" },
        { brand: "STELLA & CHEWY'S", pct: "36%", product: "Raw Blend Lamb, Beef & Venison" },
        { brand: "STELLA & CHEWY'S", pct: "35%", product: "Raw Blend Duck, Chicken, Quail" },
        { brand: "STELLA & CHEWY'S", pct: "33%", product: "Raw Coated Kibble Cage-Free Chicken Recipe" },
      ],
      Cans: [
        { brand: "TIKI DOG MEATY HIGH PROTEIN DIET", pct: "14%", product: "Chicken Recipe in Broth" },
        { brand: "TIKI DOG MEATY HIGH PROTEIN DIET", pct: "14%", product: "Chicken with Salmon Recipe in Broth" },
        { brand: "TIKI DOG MEATY HIGH PROTEIN DIET", pct: "14%", product: "Chicken with EGG Recipe in Broth" },
        { brand: "OPEN FARM", pct: "12%", product: "Salmon & Cod Toppers" },
        { brand: "OPEN FARM", pct: "12%", product: "Arctic Char" },
        { brand: "OPEN FARM", pct: "10%", product: "Salmon" },
        { brand: "ORIJEN", pct: "11%", product: "Tundra Stew" },
        { brand: "ORIJEN", pct: "11%", product: "Regional Red Stew" },
        { brand: "ORIJEN", pct: "11%", product: "Chicken Stew" },
        { brand: "ORIJEN", pct: "11%", product: "Original Stew" },
        { brand: "ORIJEN", pct: "11%", product: "Puppy Stew" },
        { brand: "LEAN CUTS", pct: "11%", product: "Salmon" },
        { brand: "LEAN CUTS", pct: "10.4%", product: "Beef" },
        { brand: "LEAN CUTS", pct: "10%", product: "Beef & Chicken" },
        { brand: "TIKKI DOG PETITES", pct: "10%", product: "Chicken Recipe in Lobster Consomme" },
        { brand: "TIKKI DOG PETITES", pct: "10%", product: "Chicken Recipe in Crab Consomme" },
        { brand: "TIKKI DOG PETITES", pct: "10%", product: "Chicken & Tuna Recipe in Chicken Consomme" },
        { brand: "FIRST MATE", pct: "11%", product: "Wild Pacific Salmon" },
        { brand: "FIRST MATE", pct: "11%", product: "Wild Pacific Salmon & Rice Formula" },
        { brand: "FIRST MATE", pct: "9%", product: "Free Run Chicken" },
        { brand: "FIRST MATE", pct: "9%", product: "Cage Free Chicken & Rice Formula" },
        { brand: "NOW FRESH", pct: "11%", product: "Chicken & Broth Blend" },
        { brand: "PERFORMATRIN PRIME", pct: "11%", product: "Puppy Chicken Formula Pate" },
        { brand: "PERFORMATRIN PRIME", pct: "10%", product: "Adult Chicken Formula Pate" },
        { brand: "PERFORMATRIN PRIME", pct: "9%", product: "Adult Turkey & Chicken Formula Entrée" },
        { brand: "PERFORMATRIN PRIME", pct: "9%", product: "Adult Chicken Formula Stew" },
        { brand: "CANADA FRESH", pct: "9.5%", product: "Lamb" },
        { brand: "CANADA FRESH", pct: "9.5%", product: "Beef" },
        { brand: "CANADA FRESH", pct: "9%", product: "Chicken" },
      ],
      Treats: [
        { brand: "JUST 2 SIMPLE INGREDIENT", pct: "84.6%", product: "Chicken & Parsley" },
        { brand: "JUST 2 SIMPLE INGREDIENT", pct: "81.8%", product: "Chicken & Cranberry" },
        { brand: "JUST 2 SIMPLE INGREDIENT", pct: "81.6%", product: "Chicken & Peanut Butter" },
        { brand: "CRUMP'S NATURAL", pct: "70%", product: "Lamb Chops" },
        { brand: "CRUMP'S NATURAL", pct: "63%", product: "Traditional Liver Fillets" },
        { brand: "CRUMP'S NATURAL", pct: "61%", product: "Beef Tender Sticks" },
        { brand: "CRUMP'S NATURAL", pct: "60%", product: "Mini Trainers Beef Liver" },
        { brand: "CRUMP'S NATURAL", pct: "54%", product: "Mini Trainers Pork Hearts" },
        { brand: "PURE BITES", pct: "74%", product: "Chicken Breast" },
        { brand: "PURE BITES", pct: "70%", product: "Cod Skin Jerky" },
        { brand: "PURE BITES", pct: "70%", product: "Chicken Breast" },
        { brand: "PURE BITES", pct: "67%", product: "Duck Liver" },
        { brand: "PURE BITES", pct: "65%", product: "Lamb Liver" },
        { brand: "PURE BITES", pct: "64%", product: "Beef Liver" },
        { brand: "PURE BITES", pct: "62%", product: "Wild-Caught Cheese" },
        { brand: "PURE BITES", pct: "53%", product: "Bison Liver" },
        { brand: "SKALLIWAGES", pct: "80%", product: "Kangaroo Jerky" },
        { brand: "SKALLIWAGES", pct: "77%", product: "Venison Jerky" },
        { brand: "SKALLIWAGES", pct: "64.7%", product: "Sundried Sardines" },
        { brand: "SKALLIWAGES", pct: "53.1%", product: "Bison Liver" },
        { brand: "T&T SYDNEY'S HARBOUR", pct: "76.8%", product: "Cod Skin for Dogs" },
        { brand: "T&T SYDNEY'S HARBOUR", pct: "70%", product: "Pacific Freshwater Rainbow Smell" },
        { brand: "ULTRA", pct: "60%", product: "Beef Lungs Tenders" },
        { brand: "ULTRA", pct: "60%", product: "PIG Ears" },
        { brand: "ULTRA", pct: "55%", product: "Coated Half Cow Ears Beef & Bully" },
        { brand: "ULTRA", pct: "55%", product: "Coated Cow Ears Chicken Coated" },
        { brand: "REDBARN", pct: "80%", product: "Bully Slices" },
        { brand: "REDBARN", pct: "70%", product: "Choppers" },
        { brand: "REDBARN", pct: "78%", product: "Collagen Slices" },
        { brand: "PETCENTER INC", pct: "98%", product: "Steer Sticks (Steer Pizzle)" },
        { brand: "PETCENTER INC", pct: "58%", product: "Beef Stakes" },
        { brand: "SUPER GOOD PETS", pct: "65%", product: "Lamb Liver" },
        { brand: "SUPER GOOD PETS", pct: "65%", product: "Pork Liver" },
        { brand: "SUPER GOOD PETS", pct: "64%", product: "Beef Liver" },
        { brand: "WILD PACIFIC", pct: "74%", product: "Salmon Strips" },
        { brand: "WILD PACIFIC", pct: "60%", product: "Salmon Sushi" },
        { brand: "OPEN FARM", pct: "77%", product: "Cod Skins (Both)" },
        { brand: "OPEN FARM", pct: "66%", product: "Pasture-Raised Lamb Liver" },
        { brand: "OPEN FARM", pct: "62%", product: "Grass Fed Beef Liver" },
        { brand: "VITAL ESSENTIALS", pct: "65%", product: "Chicken Hearts" },
        { brand: "VITAL ESSENTIALS", pct: "60%", product: "Minnows" },
        { brand: "BENNY BULLY'S", pct: "70%", product: "Purple Sweet Potato & Beef Hearts" },
        { brand: "BENNY BULLY'S", pct: "68%", product: "Beef Liver Chops" },
        { brand: "BENNY BULLY'S", pct: "59%", product: "Beef Liver & Real Sweet Potato" },
        { brand: "BENNY BULLY'S", pct: "56%", product: "Beef Liver & Real Pumpkin" },
        { brand: "K9 NATURAL", pct: "60%", product: "New Zealand Grassfed Lamb Green Tripe" },
        { brand: "K9 NATURAL", pct: "57%", product: "Green Mussels" },
        { brand: "PERFORMATRIN ULTRA", pct: "86.4%", product: "Supreme Bully Stick" },
        { brand: "PERFORMATRIN ULTRA", pct: "86.4%", product: "Bully Braid" },
        { brand: "PERFORMATRIN ULTRA", pct: "82%", product: "Bully Stick (REG)" },
        { brand: "PERFORMATRIN ULTRA", pct: "80%", product: "Collagen Ring" },
        { brand: "PERFORMATRIN ULTRA", pct: "80%", product: "Beef Tender" },
        { brand: "PERFORMATRIN ULTRA", pct: "75%", product: "FDR Turkey" },
        { brand: "PERFORMATRIN ULTRA", pct: "65%", product: "FDR Lamb Liver" },
        { brand: "PERFORMATRIN ULTRA", pct: "64%", product: "FDR Beef Liver" },
        { brand: "PERFORMATRIN ULTRA", pct: "62%", product: "FDR Chicken Liver" },
      ],
    },
    "High Fat": {
      Kibble: [
        { brand: "PRIMAL RAW", pct: "23%", product: "Chicken Recipe" },
        { brand: "PRIMAL RAW", pct: "23%", product: "Small Breed Chicken Recipe" },
        { brand: "PRIMAL RAW", pct: "22%", product: "Puppy" },
        { brand: "PRIMAL RAW", pct: "21%", product: "Beef Recipe" },
        { brand: "PRIMAL RAW", pct: "21%", product: "Fish & Pork Recipe" },
        { brand: "ORIJEN", pct: "20%", product: "Puppy" },
        { brand: "ORIJEN", pct: "20%", product: "Amazing Grains Puppy" },
        { brand: "ORIJEN", pct: "18%", product: "Small Breed" },
        { brand: "ORIJEN", pct: "18%", product: "Original" },
        { brand: "ORIJEN", pct: "18%", product: "Regional Red" },
        { brand: "ORIJEN", pct: "18%", product: "Six Fish" },
        { brand: "ORIJEN", pct: "18%", product: "Amazing Grains Original" },
        { brand: "ORIJEN", pct: "18%", product: "Amazing Grains Regional Red" },
        { brand: "ACANA", pct: "20%", product: "Healthy Grains Puppy" },
        { brand: "ACANA", pct: "20%", product: "Puppy Sea & Farm" },
        { brand: "ACANA", pct: "20%", product: "Puppy Small Breed Recipe" },
        { brand: "ACANA", pct: "20%", product: "Puppy" },
        { brand: "SQUARE PET VFS", pct: "20%", product: "Red Meat Adult & Puppy" },
        { brand: "SQUARE PET VFS", pct: "20%", product: "TK & CK" },
        { brand: "ROYAL CANIN", pct: "20%", product: "Digestive Care Small" },
        { brand: "ROYAL CANIN", pct: "20%", product: "Fussy Appetite Small" },
        { brand: "ROYAL CANIN", pct: "18%", product: "Yorkshire Puppy" },
        { brand: "ROYAL CANIN", pct: "18%", product: "Puppy X-Small" },
        { brand: "PURINA PROPLAN", pct: "18%", product: "Puppy Under One Year Chicken & Rice" },
        { brand: "PURINA PROPLAN", pct: "18%", product: "Puppy Under One Year Development 30/20 Chicken & Rice Formula" },
        { brand: "FIRSTMATE", pct: "20%", product: "High Performance for Active Dogs & Puppies" },
        { brand: "FIRSTMATE", pct: "18%", product: "Pacific Ocean Fish Meal Endurance / Puppy Formula" },
        { brand: "PRIME", pct: "20%", product: "Puppy Small Breed Chicken & Rice" },
        { brand: "PRIME", pct: "18%", product: "Puppy Chicken & Rice Formula" },
        { brand: "GO! SOLUTIONS", pct: "18%", product: "Puppy Carnivore Grain Free Chk, Try, Dk" },
        { brand: "NOW FRESH", pct: "18%", product: "Small Breed Puppy Trky, Slm & Duck" },
      ],
      Cans: [
        { brand: "BLUE WILDERNESS", pct: "9%", product: "Beef & Chicken Grill" },
        { brand: "BLUE WILDERNESS", pct: "9%", product: "Turkey & Chicken Grill" },
        { brand: "BLUE WILDERNESS", pct: "9%", product: "Duck & Chicken Grill" },
        { brand: "BLUE WILDERNESS", pct: "8%", product: "Chicken & Salmon Grill" },
        { brand: "ULTRA", pct: "8%", product: "Duck & Pea Pate" },
        { brand: "ZIGNATURE", pct: "8%", product: "Trout & Salmon Formula" },
        { brand: "FIRST MATE", pct: "8%", product: "Pork & Rice Formula" },
        { brand: "FIRST MATE", pct: "8%", product: "Cage Free Turkey & Rice Formula" },
        { brand: "FIRST MATE", pct: "8%", product: "Cage Free Turkey Formula Whipped Pate" },
        { brand: "FIRST MATE", pct: "8%", product: "Pork & Apple Formula Whipped Pate" },
        { brand: "CANADA FRESH", pct: "8.5%", product: "Beef" },
        { brand: "CANADA FRESH", pct: "8.5%", product: "Lamb" },
        { brand: "TRIPETT by PetKind", pct: "8%", product: "Green Beef Tripe, Duck & Salmon" },
        { brand: "OPEN FARM", pct: "8%", product: "Salmon" },
        { brand: "OPEN FARM", pct: "8%", product: "Arctic Char" },
        { brand: "LEAN CUTS", pct: "8%", product: "Salmon" },
        { brand: "PURINA ONE", pct: "8%", product: "True Instinct with Real Beef & Bison" },
        { brand: "PURINA ONE", pct: "8%", product: "True Instinct with Real Turkey & Venison" },
        { brand: "PURINA ONE", pct: "10%", product: "True Instinct Lamb & Brown Rice Entrée" },
        { brand: "PURINA ONE", pct: "9%", product: "True Instinct With Real Turkey & Venison" },
        { brand: "PURINA ONE", pct: "9%", product: "True Instinct With Real Beef & Bison" },
        { brand: "PURINA PROPLAN", pct: "9%", product: "Complete Essentials Chicken & Rice" },
        { brand: "PURINA PROPLAN", pct: "9%", product: "Complete Essentials Beef & Rice" },
        { brand: "PURINA PROPLAN", pct: "9%", product: "Weight Management Turkey & Rice" },
        { brand: "BLUE WILDERNESS", pct: "10%", product: "Turkey & Chicken Grill" },
        { brand: "BLUE WILDERNESS", pct: "10%", product: "Duck & Chicken Grill" },
        { brand: "BLUE WILDERNESS", pct: "10%", product: "Chicken & Salmon Grill" },
        { brand: "BLUE WILDERNESS", pct: "9%", product: "Beef & Chicken Grill" },
        { brand: "ULTRA", pct: "10%", product: "Venison & Sweet Potato Pate" },
        { brand: "ULTRA", pct: "10%", product: "Fish & Sweet Potato Pate" },
        { brand: "ULTRA", pct: "10%", product: "G.F. Chicken Pate Puppy" },
        { brand: "ULTRA", pct: "9%", product: "G.F. Chicken Dinner in Gravy Adult" },
        { brand: "WERUVA", pct: "10%", product: "PAW Lickin' Chicken" },
        { brand: "WERUVA", pct: "10%", product: "Meals 'n More PAW Lickin' Chicken" },
        { brand: "K9 NATURAL", pct: "9.5%", product: "Chicken Feast" },
        { brand: "ZIGNATURE", pct: "9.5%", product: "Pork Formula" },
        { brand: "ZIGNATURE", pct: "9.5%", product: "Turkey Formula" },
        { brand: "ZIGNATURE", pct: "9%", product: "Kangaroo Formula" },
        { brand: "GO! SOLUTIONS", pct: "9.5%", product: "Carnivore G.F. Chicken, Turkey & Duck Stew" },
        { brand: "GO! SOLUTIONS", pct: "9%", product: "Skin & Coat Care Turkey + Salmon Pate With Grains" },
        { brand: "ACANA", pct: "9.5%", product: "Puppy Recipe In Bone Broth" },
        { brand: "STELLA & CHEWY'S", pct: "10%", product: "Red Meat Medley" },
        { brand: "STELLA & CHEWY'S", pct: "9%", product: "Cage Free Turkey Recipe" },
        { brand: "STELLA & CHEWY'S", pct: "9%", product: "Grass-Fed BEEF Recipe" },
        { brand: "STELLA & CHEWY'S", pct: "9%", product: "Grain Free Cage Free Chicken Recipe" },
        { brand: "NATURALS", pct: "9%", product: "Grain-Free Puppy Chicken Recipe" },
        { brand: "BLUE BUFFALO", pct: "9%", product: "Homestead Recipe" },
        { brand: "BLUE BUFFALO", pct: "9%", product: "Chicken Dinner with Garden Vegetables" },
      ],
      Treats: [
        { brand: "K9 NATURAL", pct: "38%", product: "Lamb Organs" },
        { brand: "K9 NATURAL", pct: "27%", product: "Chicken Feast" },
        { brand: "STELLA & CHEWY'S", pct: "36.9%", product: "Lamb Recipe" },
        { brand: "STELLA & CHEWY'S", pct: "31%", product: "Wild Weenies Beef Recipe" },
        { brand: "OPEN FARM", pct: "40%", product: "Turkey Dog Treats" },
        { brand: "OPEN FARM", pct: "35%", product: "Beef Dog Treats" },
        { brand: "OPEN FARM", pct: "32%", product: "Chicken Dog Treats" },
        { brand: "OPEN FARM", pct: "22%", product: "Pork Dog Treats" },
        { brand: "VITAL ESSENTIALS", pct: "35%", product: "Duck Bites" },
        { brand: "VITAL ESSENTIALS", pct: "34%", product: "Beef Tripe Bites" },
        { brand: "VITAL ESSENTIALS", pct: "20%", product: "Chicken Hearts" },
        { brand: "JERKY BITES", pct: "21%", product: "Duck With Cranberry Recipe" },
        { brand: "CHARLES BEAR NUGGETS", pct: "35%", product: "Mini Sticks Duck Meat Sticks" },
        { brand: "CHARLES BEAR NUGGETS", pct: "22%", product: "P.B. & Beary" },
        { brand: "CHARLES BEAR NUGGETS", pct: "22%", product: "Shepherd's Pie" },
        { brand: "WILD PUREBITES", pct: "30%", product: "Cheddar Cheese" },
        { brand: "WILD PUREBITES", pct: "30%", product: "Hip & Joint" },
        { brand: "WILD PUREBITES", pct: "22%", product: "Gut & Digestion" },
        { brand: "THE HONEST KITCHEN", pct: "20%", product: "Slow Roasted Chicken & Salmon Recipe" },
      ],
    },
    "High Fiber": {
      Kibble: [
        { brand: "SCIENCE DIET", pct: "18%", product: "Perfect Weight & Joint Support Chicken & Brown Rice Recipe" },
        { brand: "SCIENCE DIET", pct: "13%", product: "Perfect Weight Chicken & Brown Rice Recipe" },
        { brand: "SCIENCE DIET", pct: "13%", product: "Small & Mini Oral Care Chicken, Rice & Barley Recipe" },
        { brand: "SCIENCE DIET", pct: "12%", product: "Oral Care Chicken, Brown Rice & Barley Recipe" },
        { brand: "NATURAL BALANCE", pct: "10.5%", product: "Fat Dog" },
        { brand: "OPEN FARM", pct: "10%", product: "Healthy Weight Chicken & Whitefish Recipe" },
        { brand: "GO! SOLUTIONS", pct: "10%", product: "Weight Management + Joint Care G.F. Salmon Recipe" },
        { brand: "GO! SOLUTIONS", pct: "10%", product: "Weight Management + Joint Care G.F. Chicken Recipe" },
        { brand: "PRIME", pct: "9%", product: "Oral Care Chicken & Rice Formula" },
        { brand: "PRIME", pct: "6.5%", product: "Healthy Weight Small Breed Chk & Rice" },
        { brand: "PRIME", pct: "6%", product: "Healthy Weight Lamb & Brown Rice" },
        { brand: "FIRSTMATE", pct: "8%", product: "Cage Free Duck Meal & Pumpkin" },
        { brand: "FIRSTMATE", pct: "8%", product: "Pacific Ocean Fish Meal Endurance" },
        { brand: "FIRSTMATE", pct: "8%", product: "Pacific Ocean Fish Meal Original" },
        { brand: "FIRSTMATE", pct: "7.5%", product: "Australian Lamb Meal Formula" },
        { brand: "FIRSTMATE", pct: "7%", product: "Senior / Weight Control Formula" },
        { brand: "FIRSTMATE", pct: "7%", product: "Free Range Lamb Meal & Oat Formula" },
        { brand: "FIRSTMATE", pct: "7%", product: "Wild Pacific Caught Fish Meal & Oats" },
        { brand: "FIRSTMATE", pct: "7%", product: "Cage Free Duck Meal & Oats Formula" },
        { brand: "FIRSTMATE", pct: "7%", product: "Cage Free Chicken Meal & Oats Formula" },
        { brand: "FIRSTMATE", pct: "7%", product: "New Zealand Beef Meal & Oats Formula" },
        { brand: "FIRSTMATE", pct: "7%", product: "High Performance For Active Dogs & Puppies" },
        { brand: "ACANA", pct: "8%", product: "Light & Fit Recipe" },
        { brand: "ACANA", pct: "6%", product: "Ranchlands" },
        { brand: "ACANA", pct: "6%", product: "Senior Recipe" },
        { brand: "ACANA", pct: "6%", product: "Pork with Squash Recipe" },
        { brand: "ACANA", pct: "6%", product: "Duck With Pear Recipe" },
        { brand: "ACANA", pct: "6%", product: "Lamb With Apple" },
        { brand: "NOW FRESH", pct: "7.5%", product: "Good Gravy Beef Recipe For Seniors Coated in Bone Broth" },
        { brand: "NOW FRESH", pct: "7%", product: "Senior G.F. Recipe with Turkey, Salmon & Duck" },
        { brand: "STELLA & CHEWY'S", pct: "6%", product: "Small Breed Red Meat Recipe Lamb, Beef, Venison" },
        { brand: "STELLA & CHEWY'S", pct: "6%", product: "Raw Blend Lamb, Beef, Venison" },
        { brand: "BLUE WILDERNESS", pct: "6%", product: "Adult With Chicken" },
        { brand: "ULTRA", pct: "6%", product: "Healthy Weight Recipe with Salmon" },
        { brand: "ULTRA", pct: "6%", product: "G.F. Senior" },
      ],
      Cans: [
        { brand: "NATURAL BALANCE", pct: "5%", product: "Fat Dog With Real Chicken & Salmon Specialized Nutrition" },
        { brand: "NATURAL BALANCE", pct: "3%", product: "Sensitive Skin & Stomach Formula With Salmon & Brown Rice" },
        { brand: "SCIENCE DIET", pct: "4%", product: "Perfect Weight Adult Chicken & Vegetable Entrée" },
        { brand: "SCIENCE DIET", pct: "4%", product: "Perfect Weight Adult Hearty Vegetable & Chicken Stew" },
        { brand: "BLUE", pct: "3%", product: "Weight Care Formula With Wholesome Grains" },
        { brand: "BLUE", pct: "3%", product: "Digestive Care Formula With Wholesome Grains" },
      ],
      Treats: [
        { brand: "HEALTH SECTION", pct: "41.5%", product: "Cranimals Urinary Tract" },
        { brand: "HEALTH SECTION", pct: "40%", product: "Firmup! Pumpkin Digestive Aid" },
        { brand: "HEALTH SECTION", pct: "40%", product: "Firmup! Pumpkin + Cranberry Digestive Aid" },
        { brand: "PUREBITES", pct: "6%", product: "Gut & Digestion" },
        { brand: "WELLNESS WHIMZEES", pct: "9%", product: "Mostly all" },
        { brand: "CRUMP'S NATURALS", pct: "15%", product: "Plaque Busters Pumpkin Spice" },
        { brand: "CRUMP'S NATURALS", pct: "12%", product: "Plaque Busters Bacon Flavored" },
        { brand: "CRUMP'S NATURALS", pct: "12%", product: "Original Dental Sticks" },
        { brand: "CRUMP'S NATURALS", pct: "10%", product: "Plaque Busters Advanced Whole Mouth Care" },
        { brand: "GREENIES", pct: "6%", product: "Mostly all" },
        { brand: "ULTRA", pct: "7%", product: "Dental Chew With Peppermint Oil & Coconut oil" },
        { brand: "FRUITABLES", pct: "8%", product: "Pumpkin & Cranberry" },
        { brand: "FRUITABLES", pct: "8%", product: "Pumpkin & Apple" },
        { brand: "FRUITABLES", pct: "8%", product: "Pumpkin & Banana" },
        { brand: "FRUITABLES", pct: "8%", product: "Crispy Bacon & Apple" },
        { brand: "FRUITABLES", pct: "8%", product: "Pumpkin & Blueberry" },
        { brand: "FRUITABLES", pct: "7%", product: "Skinny Minis Chicken Flavor" },
        { brand: "FRUITABLES", pct: "7%", product: "Pumpkin & Berry" },
        { brand: "FRUITABLES", pct: "7%", product: "Pumpkin & Mango" },
        { brand: "NATURALS", pct: "9.5%", product: "Chicken Recipe" },
        { brand: "NATURALS", pct: "9.5%", product: "Turducken Recipe" },
        { brand: "NATURALS", pct: "9.5%", product: "Pork Liver Recipe" },
        { brand: "GET THE DUCK OUTTA HERE!", pct: "7%", product: "Premium Soft & Chewy Duck & Cranberry" },
        { brand: "BE GOOD BITES", pct: "7%", product: "Turkey Recipe Both" },
        { brand: "BE GOOD BITES", pct: "7%", product: "Wild-Caught Salmon Recipe" },
        { brand: "BE GOOD BITES", pct: "6%", product: "Grass Fed Beef Recipe" },
        { brand: "VITAL ESSENTIALS", pct: "6%", product: "Rabbit Bites" },
        { brand: "YARRI", pct: "6%", product: "Duck + Apple & Cheese" },
        { brand: "OLD MOTHER HUBBARD", pct: "6.5%", product: "Original Mix" },
        { brand: "ULTRA", pct: "6%", product: "Coated Cow Ears Chicken Coated" },
        { brand: "ULTRA", pct: "6%", product: "Coated Half Cow Ears Beef & Bully Coated" },
      ],
    },
    "Low Protein": {
      Kibble: [
        { brand: "NATURAL BALANCE", pct: "18%", product: "Plant Powered Vegetarian" },
        { brand: "NATURAL BALANCE", pct: "20%", product: "Venison & Sweet Potato" },
        { brand: "NATURAL BALANCE", pct: "20%", product: "Bison & Sweet Potato" },
        { brand: "FIRSTMATE", pct: "18%", product: "Pacific Ocean with WG Control SNR Formula" },
        { brand: "SCIENCE DIET", pct: "15.5%", product: "Adult 7+ Small Bites Chkn & Brly, Rice" },
        { brand: "SCIENCE DIET", pct: "20%", product: "Small & Mini Adult 1-6 Chkn & BR" },
        { brand: "SCIENCE DIET", pct: "20%", product: "Perfect Digestion Adult 1-6" },
        { brand: "SCIENCE DIET", pct: "20%", product: "Adult 1-6 Small Bites" },
        { brand: "SCIENCE DIET", pct: "20%", product: "Sensitive Stomach & Skin Adult" },
        { brand: "SCIENCE DIET", pct: "20%", product: "Oral Care" },
      ],
      Cans: [
        { brand: "OPEN FARM", pct: "2%", product: "Grass Fed Beef Bone Broth" },
        { brand: "OPEN FARM", pct: "2%", product: "Harvest Chicken Bone Broth" },
        { brand: "THE HONEST KITCHEN", pct: "3%", product: "Turkey & Pumpkin Stew" },
        { brand: "THE HONEST KITCHEN", pct: "3%", product: "Chicken & Pumpkin Stew" },
        { brand: "THE HONEST KITCHEN", pct: "4.5%", product: "Beef Stew (Bone Broth Pour Overs)" },
        { brand: "THE HONEST KITCHEN", pct: "5%", product: "Turkey & Salmon Stew" },
        { brand: "NATURAL BALANCE", pct: "5%", product: "Sweet Potato & Salmon" },
        { brand: "NATURAL BALANCE", pct: "5%", product: "Plant Powered Vegetarian" },
        { brand: "NATURAL BALANCE", pct: "5%", product: "Duck & Potato" },
        { brand: "NATURAL BALANCE", pct: "5.5%", product: "Chicken & Sweet Potato" },
      ],
      Treats: [
        { brand: "ZUKE'S MINI NATURALS", pct: "5%", product: "Duck Recipe" },
        { brand: "ZUKE'S MINI NATURALS", pct: "8%", product: "Rabbit Recipe" },
        { brand: "ETTA SAYS! SIT!", pct: "6.4%", product: "Training Treats Oats & Peanut Recipe" },
        { brand: "LOVE PUFFS", pct: "7%", product: "Apple & Carrot" },
        { brand: "LOVE PUFFS", pct: "7%", product: "Blueberry" },
        { brand: "BYE-BYE STRIKES", pct: "7%", product: "Pumpkin & Ginger" },
        { brand: "ULTRA TRAINING BITES", pct: "7.5%", product: "Sweet Potato Recipe" },
        { brand: "LORD JAMESON", pct: "7.5%", product: "Celebration Bash Organic Dog Treats (Made with Peanut Butter)" },
        { brand: "FRUITABLES SKINNY MINIS", pct: "8%", product: "Rotisserie Chicken" },
        { brand: "FRUITABLES SKINNY MINIS", pct: "8%", product: "Pumpkin & Mango" },
        { brand: "FRUITABLES SKINNY MINIS", pct: "8%", product: "Pumpkin & Berry" },
        { brand: "FRUITABLES SKINNY MINIS", pct: "8%", product: "Grilled Bison Flavor" },
        { brand: "PETGREENS", pct: "8%", product: "Lamb Recipe" },
        { brand: "HONEST KITCHEN GOAT MILK", pct: "8%", product: "Blueberries & Vanilla 8oz" },
        { brand: "SWEET DREAM", pct: "8%", product: "Banana & Honey" },
        { brand: "NORTHERN", pct: "8%", product: "Pumpkin Pie 500g" },
        { brand: "NORTHERN", pct: "8%", product: "Lamb & Pumpkin" },
        { brand: "STELLA & CHEWY'S", pct: "8%", product: "Bacon & Chicken Recipe" },
        { brand: "STELLA & CHEWY'S", pct: "8%", product: "Bacon & Beef Recipe" },
        { brand: "STELLA & CHEWY'S", pct: "8%", product: "Bacon & Duck Recipe" },
        { brand: "OPEN FARM BE GOOD BITES", pct: "8%", product: "Wild-Caught Salmon Recipe" },
        { brand: "OPEN FARM BE GOOD BITES", pct: "8%", product: "Turkey Recipe" },
        { brand: "OPEN FARM BE GOOD BITES", pct: "8%", product: "Grass-Fed Beef Recipe" },
      ],
    },
    "Low Fat": {
      Kibble: [
        { brand: "DIAMOND CARE MINI", pct: "6%", product: "Weight Management Formula (Mini)" },
        { brand: "DIAMOND CARE MAXI", pct: "8%", product: "Weight Management Formula (Maxi)" },
        { brand: "NATURAL BALANCE", pct: "7.5%", product: "Low Calories + Big Flavor Chicken, Salmon & Barley" },
        { brand: "SCIENCE DIET", pct: "8%", product: "Perfect Weight Adult Chicken Recipe" },
        { brand: "PRIME", pct: "8%", product: "Healthy Weight Adult 1+ Lamb Meal & Brown Rice Formula" },
        { brand: "ULTRA", pct: "8%", product: "Wholesome Grains Healthy Weight Recipe with Salmon" },
        { brand: "FIRSTMATE", pct: "8%", product: "Senior / Weight Control Formula" },
        { brand: "FIRSTMATE", pct: "8%", product: "Pacific Ocean with WG Control SNR Formula" },
        { brand: "ROYAL CANIN", pct: "9%", product: "DG Weight Care Small Petit" },
        { brand: "SCIENCE DIET", pct: "9%", product: "Small & Mini Adult up to 25lb Perfect Weight Chicken Recipe" },
        { brand: "BARKER'S COMPLETE", pct: "10%", product: "Adult Chicken & Vegetable Flavor" },
        { brand: "BARKER'S COMPLETE", pct: "10%", product: "Adult Beef & Vegetable Flavor" },
        { brand: "PRIME", pct: "10%", product: "Senior 7+ years Lamb Meal & Brown Rice Formula" },
        { brand: "PRIME", pct: "10%", product: "Adult 11+ months Healthy Weight Chicken & Rice Formula" },
        { brand: "NATURAL BALANCE", pct: "10%", product: "LID Sweet Potato & Venison" },
        { brand: "NATURAL BALANCE", pct: "10%", product: "LID Sweet Potato & Bison" },
        { brand: "NATURAL BALANCE", pct: "10%", product: "LID Duck & Potato" },
        { brand: "NATURAL BALANCE", pct: "10%", product: "LID Salmon & Sweet Potato" },
        { brand: "BLUE BUFFALO", pct: "10%", product: "Senior Chicken & Brown Rice Life Protection Formula" },
        { brand: "CANADIAN NATURALS", pct: "10%", product: "LID Sweet Potato & Salmon From Puppy to Adult" },
        { brand: "CANADIAN NATURALS", pct: "10%", product: "Potato & Duck From Puppy & Adult" },
        { brand: "GO! SOLUTIONS", pct: "10%", product: "Weight Management + Joint Care GF Salmon" },
        { brand: "GO! SOLUTIONS", pct: "10%", product: "Weight Management + Joint Care GF Chicken" },
        { brand: "GO! SOLUTIONS", pct: "10%", product: "Sensitivities LID GF Salmon Recipe" },
        { brand: "FIRST MATE", pct: "10%", product: "LID Pacific Ocean Fish Meals Original Formula Small Bites" },
        { brand: "FIRST MATE", pct: "10%", product: "LID Pacific Fish Meal Original Formula Puppy & Adult" },
        { brand: "SCIENCE DIET", pct: "10.5%", product: "Perfect Weight & Joint Support Chicken & Brown Rice" },
        { brand: "SCIENCE DIET", pct: "10.5%", product: "Adult 7+ Small Bites Chicken Meal, Barley & Rice Recipe" },
      ],
      Cans: [
        { brand: "OPEN FARM", pct: "0.1%", product: "Grass-Fed Beef Bone Broth" },
        { brand: "OPEN FARM", pct: "0.1%", product: "Harvest Chicken Bone Broth" },
        { brand: "THE HONEST KITCHEN", pct: "0.5%", product: "Pumpkin Pour Overs 100% Natural Topper Turkey & Pumpkin Stew" },
        { brand: "THE HONEST KITCHEN", pct: "0.25%", product: "Pumpkin Pour Overs Chicken & Pumpkin Stew" },
        { brand: "THE HONEST KITCHEN", pct: "1%", product: "Bone Broth Pour Overs Turkey & Salmon Stew" },
        { brand: "STELLA & CHEWY'S", pct: "0.5%", product: "Bountiful Bone Broth (Chicken)" },
        { brand: "STELLA & CHEWY'S", pct: "0.1%", product: "Cage-Free Chicken Broth Topper" },
        { brand: "STELLA & CHEWY'S", pct: "0.1%", product: "Grass-Fed Beef Broth Topper" },
        { brand: "STELLA & CHEWY'S", pct: "0.1%", product: "Bountiful Bone Broth Beef Bone" },
        { brand: "WERUVA B.F.F.", pct: "1%", product: "OH SO NICE With SirLoin Tips & Rice Cooked in Broth" },
        { brand: "WERUVA B.F.F.", pct: "2%", product: "ROLL THE DICE Chicken Breast & Rice Cooked in Broth" },
        { brand: "WERUVA MEALS 'N MORE", pct: "1%", product: "Steak Frites" },
        { brand: "WERUVA MEALS 'N MORE", pct: "1%", product: "Wok the Dog" },
        { brand: "WERUVA MEALS 'N MORE", pct: "1%", product: "Amazon Livin' Recipe" },
        { brand: "WERUVA MEALS 'N MORE", pct: "1%", product: "Grandma's Chicken Soup" },
        { brand: "WERUVA DOGS IN KITCHEN", pct: "1.5%", product: "The Double Dip" },
        { brand: "WERUVA DOGS IN KITCHEN", pct: "1.5%", product: "Funk in the Trunk" },
        { brand: "WERUVA DOGS IN KITCHEN", pct: "2%", product: "Fowl Ball" },
        { brand: "MERRICK", pct: "2%", product: "Memphis with Glazed Chicken" },
        { brand: "MERRICK", pct: "2%", product: "Kansas City with Chopped Pork" },
        { brand: "MERRICK", pct: "2%", product: "One Pot Stews Colossal Chicken Dinner" },
        { brand: "NATURAL BALANCE", pct: "2.5%", product: "Fat Dogs Chicken & Salmon Recipe in Broth" },
        { brand: "NATURAL BALANCE", pct: "3%", product: "Plant Powered LID Vegetarian Recipe" },
        { brand: "NATURAL BALANCE", pct: "3.5%", product: "Chicken & Sweet Potato Recipe" },
        { brand: "NATURAL BALANCE", pct: "4%", product: "Sweet Potato & Salmon LID" },
        { brand: "NATURAL BALANCE", pct: "4%", product: "Sweet Potato & Venison LID" },
        { brand: "NATURAL BALANCE", pct: "4%", product: "Bison & Sweet Potato Recipe" },
        { brand: "NATURAL BALANCE", pct: "4%", product: "Duck & Potato Recipe" },
        { brand: "GO! SOLUTIONS", pct: "2.5%", product: "Carnivore Chkn, Trky, Duck" },
        { brand: "GO! SOLUTIONS", pct: "2.5%", product: "Booster Shredded Chkn, Slm" },
        { brand: "GO! SOLUTIONS", pct: "2.5%", product: "GF Ocean Stew Puppy to Adult" },
        { brand: "ZIGNATURE", pct: "4%", product: "Kangaroo Formula LID Formula" },
        { brand: "BLUE", pct: "4%", product: "Hunter's Stew" },
        { brand: "BLUE", pct: "4%", product: "Grammy's Pot Pie" },
      ],
      Treats: [
        { brand: "OPEN FARM", pct: "0.1%", product: "Cod Fish" },
        { brand: "OPEN FARM", pct: "0.8%", product: "Cod Skins Dehydrated" },
        { brand: "OPEN FARM", pct: "1.5%", product: "GET the DUCK Outta Here! Soft & Chewy Duck & Cranberry" },
        { brand: "NATURALS", pct: "1%", product: "Lamb & Date" },
        { brand: "NATURALS", pct: "1%", product: "Pork & Peach" },
        { brand: "NATURALS", pct: "3%", product: "Super Food Sticks SP & Quinoa" },
        { brand: "ETTA SAYS! SIT!", pct: "2.9%", product: "Pork & Bacon Recipe" },
        { brand: "PURINA", pct: "3.5%", product: "Beggin' Dog Snack Cheese Flavour" },
        { brand: "ULTRA TRAINING BITES", pct: "2%", product: "Sweet Potato Recipe" },
        { brand: "ZUKE'S MINI NATURALS", pct: "2%", product: "Rabbit Recipe" },
        { brand: "ZUKE'S MINI NATURALS", pct: "3%", product: "Salmon Recipe" },
        { brand: "ZUKE'S MINI NATURALS", pct: "3%", product: "Chicken Recipe" },
        { brand: "ZUKE'S MINI NATURALS", pct: "3%", product: "Duck Recipe" },
        { brand: "NORTHERN", pct: "2%", product: "Lamb & Pumpkin" },
        { brand: "NORTHERN", pct: "2%", product: "Pumpkin Pie 500g" },
        { brand: "NORTHERN", pct: "3%", product: "Lamb & Berry 500g" },
        { brand: "NORTHERN", pct: "3%", product: "Liver Licious 500g" },
        { brand: "PUREBITES", pct: "3%", product: "Chicken Breast" },
        { brand: "PUREBITES", pct: "3%", product: "Jerky Treats for DOGS Chicken Breast" },
        { brand: "MERRICK POWERBITES", pct: "3%", product: "Turducken Recipe" },
        { brand: "MERRICK POWERBITES", pct: "3%", product: "Real Chicken Recipe" },
        { brand: "MERRICK POWERBITES", pct: "3%", product: "Real Salmon Recipe" },
      ],
    },
    "Low Fiber": {
      Kibble: [
        { brand: "VFS SQPT", pct: "2.5%", product: "Low Phosphorus Formula" },
        { brand: "VFS SQPT", pct: "3%", product: "Ideal Digestion" },
        { brand: "VFS SQPT", pct: "3%", product: "Active Joints" },
        { brand: "VFS SQPT", pct: "3.5%", product: "Skin & Digestive Support" },
        { brand: "PROPLAN", pct: "3%", product: "Chicken & Rice Formula (Essentials)" },
        { brand: "PROPLAN", pct: "3%", product: "Chicken & Rice Formula (Small Breed)" },
        { brand: "PROPLAN", pct: "3%", product: "Chicken & Rice Formula (Under 1 Year)" },
        { brand: "PROPLAN", pct: "3%", product: "Under One Year Puppy" },
        { brand: "PURINA ONE", pct: "3%", product: "Lamb & Rice Formula" },
        { brand: "PURINA ONE", pct: "3%", product: "Turkey & Venison" },
        { brand: "BARKER'S", pct: "3%", product: "Chicken & Vegetable" },
        { brand: "BOREAL OVEN BAKED", pct: "3%", product: "Fresh Lamb First Ingredient" },
        { brand: "BOREAL OVEN BAKED", pct: "3%", product: "Semi Moist Fish" },
        { brand: "BOREAL OVEN BAKED", pct: "3%", product: "Semi Moist Chicken" },
        { brand: "SCIENCE DIET", pct: "3%", product: "Small & Mini (Adult 1-6 up to 25 LB) Chicken & Brown Rice Recipe" },
        { brand: "PRIME", pct: "3%", product: "Puppy Small Breed Chicken & Rice Formula" },
        { brand: "TASTE OF WILD", pct: "3%", product: "Ancient Stream Canine Recipe with Smoke-Flavored Salmon" },
        { brand: "ROYAL CANIN", pct: "3.2%", product: "Small | Adult" },
        { brand: "ROYAL CANIN", pct: "3.5%", product: "Yorkie Puppy" },
        { brand: "ROYAL CANIN", pct: "3.5%", product: "X-Small Adult" },
        { brand: "ROYAL CANIN", pct: "3.6%", product: "Digestive Care" },
        { brand: "ROYAL CANIN", pct: "3.6%", product: "Chihuahua (Adult)" },
        { brand: "ROYAL CANIN", pct: "3.8%", product: "Puppy X-Small" },
        { brand: "ROYAL CANIN", pct: "3.8%", product: "Puppy Miniature Schnauzer" },
        { brand: "MERRICK", pct: "3.5%", product: "Lil' Plates Real Chicken & Sweet Potato Recipe" },
        { brand: "CANADIAN NATURALS", pct: "3.5%", product: "Potato & Duck" },
        { brand: "CANADIAN NATURALS", pct: "3.5%", product: "Sweet Potato & Salmon Recipe" },
        { brand: "CANADIAN NATURALS", pct: "3.5%", product: "Turkey & Salmon (Large Breed)" },
        { brand: "SUMMIT", pct: "3.5%", product: "Farmstead Feast Pork & Lamb Meal" },
        { brand: "SUMMIT", pct: "3.5%", product: "Coastal Grill Chicken + Salmon" },
        { brand: "SUMMIT", pct: "3.5%", product: "Range Rotisserie Chicken + Turkey" },
        { brand: "GO! SOLUTIONS", pct: "3%", product: "Carnivore G.F. Chicken, Turkey + Duck (Adult)" },
        { brand: "GO! SOLUTIONS", pct: "3.5%", product: "Salmon + Cod Recipe" },
        { brand: "GO! SOLUTIONS", pct: "3.5%", product: "Skin & Coat Care Chicken Recipe with Grains" },
        { brand: "GO! SOLUTIONS", pct: "3.5%", product: "Turkey Recipe with Grains" },
        { brand: "GO! SOLUTIONS", pct: "3%", product: "Lamb Recipe with Grains" },
        { brand: "ORIJEN", pct: "3.5%", product: "Original (Amazing Grains)" },
        { brand: "ORIJEN", pct: "3.5%", product: "Regional Red (Amazing Grains)" },
        { brand: "ORIJEN", pct: "3.5%", product: "Chicken & Turkey and Wild-Caught Fish" },
        { brand: "PRIMAL ALL KIBBLE RAW", pct: "3%", product: "All Kibble in the Raw has 3%" },
      ],
      Cans: [
        { brand: "FIRSTMATE", pct: "0.2%", product: "Pork & Apple Formula (Whipped Pate)" },
        { brand: "FIRSTMATE", pct: "0.2%", product: "Pork & Rice Formula" },
        { brand: "FIRSTMATE", pct: "0.4%", product: "Wild Pacific Salmon Formula" },
        { brand: "FIRSTMATE", pct: "0.4%", product: "Turkey Formula (Cage-Free)" },
        { brand: "FIRSTMATE", pct: "0.5%", product: "Wild Pacific Salmon & Rice Formula" },
        { brand: "FIRSTMATE", pct: "0.5%", product: "Chicken Formula (Cage-Free)" },
        { brand: "FIRSTMATE", pct: "0.5%", product: "Chicken & Rice Formula (Cage-Free)" },
        { brand: "FIRSTMATE", pct: "0.5%", product: "Turkey & Rice Formula (Cage-Free)" },
        { brand: "LEANCUTS", pct: "0.2%", product: "Beef" },
        { brand: "LEANCUTS", pct: "0.5%", product: "Beef & Chicken" },
        { brand: "TIKIDOG (BISQUE)", pct: "0.1%", product: "Beef Recipe Bisque" },
        { brand: "TIKIDOG (BISQUE)", pct: "0.1%", product: "Duck Recipe Bisque" },
        { brand: "TIKIDOG (BISQUE)", pct: "0.1%", product: "Chicken Recipe Bisque" },
        { brand: "WERUVA", pct: "0.5%", product: "The Double Dip" },
        { brand: "WERUVA", pct: "0.5%", product: "Fowl Ball" },
        { brand: "WERUVA", pct: "0.5%", product: "Funk In the Trunk" },
        { brand: "WERUVA", pct: "0.5%", product: "Goldie Lox" },
        { brand: "WERUVA", pct: "0.5%", product: "Love Me Tender" },
        { brand: "WERUVA", pct: "0.5%", product: "Paw Lickin' Chicken" },
        { brand: "WERUVA", pct: "0.5%", product: "Green Eggs & Chicken" },
        { brand: "WERUVA", pct: "0.5%", product: "Grandma's Chicken Soup" },
        { brand: "WERUVA", pct: "0.5%", product: "Wok the Dog" },
        { brand: "WERUVA", pct: "0.5%", product: "Amazon Livin'" },
      ],
      Treats: [],
    },
  },
};

// ============================================================
// HELPERS
// ============================================================
const parsePct = (s) => parseFloat(s?.replace("%", "") || "0");

const NUTRIENT_LABELS = {
  "High Protein": { icon: "🥩", color: "#ff4d6d" },
  "High Fat":     { icon: "🔥", color: "#ff9f1c" },
  "High Fiber":   { icon: "🌿", color: "#2ec4b6" },
  "Low Protein":  { icon: "🍃", color: "#70e000" },
  "Low Fat":      { icon: "💧", color: "#48cae4" },
  "Low Fiber":    { icon: "🌾", color: "#e9c46a" },
};

const FORMAT_ICONS = { Kibble: "🦴", Cans: "🥫", Treats: "🎁" };

// ============================================================
// MAIN APP
// ============================================================
export default function App() {
  const [pet, setPet] = useState("cats");
  const [nutrient, setNutrient] = useState("High Protein");
  const [format, setFormat] = useState("All");
  const [search, setSearch] = useState("");
  const [expanded, setExpanded] = useState({});

  const nutrients = Object.keys(NUTRIENT_LABELS);
  const formats = ["All", "Kibble", "Cans", "Treats"];

  // Gather data for current pet + nutrient
  const rawData = DATABASE[pet][nutrient] || {};

  // Flatten and group by brand
  const grouped = useMemo(() => {
    const map = {};
    const fmts = format === "All" ? Object.keys(rawData) : [format];
    fmts.forEach((fmt) => {
      (rawData[fmt] || []).forEach((item) => {
        const key = item.brand.toUpperCase();
        if (!map[key]) map[key] = { brand: item.brand, items: [] };
        map[key].items.push({ ...item, fmt });
      });
    });
    // Filter by search
    const q = search.toLowerCase();
    return Object.values(map)
      .filter((g) =>
        !q ||
        g.brand.toLowerCase().includes(q) ||
        g.items.some((i) => i.product.toLowerCase().includes(q))
      )
      .sort((a, b) => {
        const maxA = Math.max(...a.items.map((i) => parsePct(i.pct)));
        const maxB = Math.max(...b.items.map((i) => parsePct(i.pct)));
        return nutrient.startsWith("High") ? maxB - maxA : maxA - maxB;
      });
  }, [pet, nutrient, format, search, rawData]);

  // Stats
  const totalBrands = grouped.length;
  const totalProducts = grouped.reduce((s, g) => s + g.items.length, 0);
  const fmtCount = format === "All"
    ? Object.keys(rawData).filter((f) => (rawData[f] || []).length > 0).length
    : 1;

  const accentColor = NUTRIENT_LABELS[nutrient]?.color || "#ff4d6d";

  const toggle = (brand) =>
    setExpanded((p) => ({ ...p, [brand]: !p[brand] }));

  return (
    <div style={{
      minHeight: "100vh",
      background: "#0d0d14",
      color: "#e8e8f0",
      fontFamily: "'Segoe UI', system-ui, sans-serif",
      maxWidth: 480,
      margin: "0 auto",
      paddingBottom: 40,
    }}>
      {/* HEADER */}
      <div style={{
        background: `linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, ${accentColor}22 100%)`,
        padding: "20px 16px 0",
        borderBottom: `2px solid ${accentColor}44`,
      }}>
        <div style={{ textAlign: "center", marginBottom: 12 }}>
          <div style={{
            fontSize: 10,
            letterSpacing: 4,
            color: accentColor,
            fontWeight: 700,
            marginBottom: 4,
          }}>✦ BOSLEY'S BY PET VALU ✦</div>
          <div style={{
            height: 4,
            background: `linear-gradient(90deg, transparent, ${accentColor}, transparent)`,
            borderRadius: 2,
            marginBottom: 10,
          }} />
          <div style={{ fontSize: 14, color: "#aaa", letterSpacing: 1 }}>
            {NUTRIENT_LABELS[nutrient]?.icon} {nutrient.toUpperCase()} · {totalBrands} BRANDS · {totalProducts} PRODUCTS
          </div>
        </div>

        {/* PET TOGGLE */}
        <div style={{ display: "flex", gap: 8, marginBottom: 12 }}>
          {["cats", "dogs"].map((p) => (
            <button key={p} onClick={() => { setPet(p); setExpanded({}); }}
              style={{
                flex: 1,
                padding: "8px 0",
                borderRadius: 8,
                border: `1.5px solid ${pet === p ? accentColor : "#333"}`,
                background: pet === p ? `${accentColor}22` : "#1a1a2e",
                color: pet === p ? accentColor : "#666",
                fontWeight: 700,
                fontSize: 13,
                letterSpacing: 2,
                cursor: "pointer",
                transition: "all 0.2s",
              }}>
              {p === "cats" ? "🐱 CATS" : "🐶 DOGS"}
            </button>
          ))}
        </div>

        {/* NUTRIENT TABS */}
        <div style={{ display: "flex", gap: 4, overflowX: "auto", paddingBottom: 0, scrollbarWidth: "none" }}>
          {nutrients.map((n) => {
            const info = NUTRIENT_LABELS[n];
            const active = nutrient === n;
            return (
              <button key={n} onClick={() => { setNutrient(n); setExpanded({}); }}
                style={{
                  flexShrink: 0,
                  padding: "8px 10px",
                  borderRadius: "8px 8px 0 0",
                  border: `1.5px solid ${active ? info.color : "#222"}`,
                  borderBottom: active ? `2px solid ${info.color}` : "1.5px solid #222",
                  background: active ? `${info.color}18` : "#111",
                  color: active ? info.color : "#555",
                  fontWeight: 700,
                  fontSize: 11,
                  letterSpacing: 1,
                  cursor: "pointer",
                  transition: "all 0.2s",
                }}>
                {info.icon} {n.toUpperCase()}
              </button>
            );
          })}
        </div>
      </div>

      {/* SEARCH + FILTERS */}
      <div style={{ padding: "14px 16px 0" }}>
        <div style={{
          display: "flex",
          alignItems: "center",
          background: "#1a1a2e",
          border: `1px solid #2a2a3e`,
          borderRadius: 10,
          padding: "8px 12px",
          marginBottom: 12,
        }}>
          <span style={{ color: "#555", marginRight: 8 }}>🔍</span>
          <input
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="SEARCH BRAND OR PRODUCT..."
            style={{
              flex: 1,
              background: "none",
              border: "none",
              outline: "none",
              color: "#ccc",
              fontSize: 12,
              letterSpacing: 1,
            }}
          />
          {search && (
            <button onClick={() => setSearch("")}
              style={{ background: "none", border: "none", color: "#555", cursor: "pointer", fontSize: 16 }}>×</button>
          )}
        </div>

        {/* Format pills */}
        <div style={{ display: "flex", gap: 8, marginBottom: 14 }}>
          {formats.map((f) => (
            <button key={f} onClick={() => setFormat(f)}
              style={{
                padding: "6px 14px",
                borderRadius: 20,
                border: `1.5px solid ${format === f ? accentColor : "#2a2a3e"}`,
                background: format === f ? `${accentColor}22` : "#1a1a2e",
                color: format === f ? accentColor : "#555",
                fontWeight: 700,
                fontSize: 11,
                letterSpacing: 1,
                cursor: "pointer",
                transition: "all 0.2s",
              }}>
              {f === "All" ? "◈ ALL" : `${FORMAT_ICONS[f]} ${f.toUpperCase()}`}
            </button>
          ))}
        </div>

        {/* Stats */}
        <div style={{ display: "flex", gap: 8, marginBottom: 14 }}>
          {[
            { val: totalBrands, label: "BRANDS" },
            { val: totalProducts, label: "PRODUCTS" },
            { val: fmtCount, label: "FORMATS" },
          ].map(({ val, label }) => (
            <div key={label} style={{
              flex: 1,
              background: "#1a1a2e",
              border: `1px solid #2a2a3e`,
              borderRadius: 10,
              padding: "10px 0",
              textAlign: "center",
            }}>
              <div style={{ fontSize: 22, fontWeight: 800, color: accentColor }}>{val}</div>
              <div style={{ fontSize: 10, color: "#555", letterSpacing: 2 }}>{label}</div>
            </div>
          ))}
        </div>

        {/* Format section header */}
        {format !== "All" && (
          <div style={{
            textAlign: "center",
            borderTop: `1px solid #2a2a3e`,
            borderBottom: `1px solid #2a2a3e`,
            padding: "8px 0",
            marginBottom: 12,
            color: accentColor,
            fontSize: 12,
            letterSpacing: 3,
            fontWeight: 700,
          }}>
            {FORMAT_ICONS[format]} {format.toUpperCase()}
          </div>
        )}
      </div>

      {/* BRAND LIST */}
      <div style={{ padding: "0 16px" }}>
        {grouped.length === 0 && (
          <div style={{ textAlign: "center", color: "#444", padding: 40, fontSize: 14 }}>
            No results found
          </div>
        )}
        {grouped.map((group) => {
          const maxPct = Math.max(...group.items.map((i) => parsePct(i.pct)));
          const minPct = Math.min(...group.items.map((i) => parsePct(i.pct)));
          const pctLabel = maxPct === minPct ? `${maxPct}%` : `${minPct}–${maxPct}%`;
          const isOpen = expanded[group.brand];
          const fmtGroups = {};
          group.items.forEach((i) => {
            if (!fmtGroups[i.fmt]) fmtGroups[i.fmt] = [];
            fmtGroups[i.fmt].push(i);
          });

          return (
            <div key={group.brand} style={{
              border: `1.5px solid ${isOpen ? accentColor + "88" : "#2a2a3e"}`,
              borderRadius: 12,
              marginBottom: 10,
              background: isOpen ? `${accentColor}08` : "#111827",
              transition: "all 0.2s",
              overflow: "hidden",
            }}>
              {/* Brand header */}
              <button onClick={() => toggle(group.brand)}
                style={{
                  width: "100%",
                  display: "flex",
                  alignItems: "center",
                  padding: "14px 14px",
                  background: "none",
                  border: "none",
                  cursor: "pointer",
                  gap: 12,
                }}>
                <div style={{
                  background: `${accentColor}22`,
                  border: `1.5px solid ${accentColor}`,
                  borderRadius: 8,
                  padding: "4px 8px",
                  color: accentColor,
                  fontWeight: 800,
                  fontSize: 12,
                  minWidth: 70,
                  textAlign: "center",
                  flexShrink: 0,
                }}>
                  {pctLabel}
                </div>
                <div style={{ flex: 1, textAlign: "left" }}>
                  <div style={{ fontWeight: 700, fontSize: 14, color: "#e8e8f0", letterSpacing: 0.5 }}>
                    {group.brand}
                  </div>
                  <div style={{ fontSize: 11, color: "#555", letterSpacing: 1, marginTop: 2 }}>
                    {group.items.length} PRODUCT{group.items.length !== 1 ? "S" : ""}
                  </div>
                </div>
                <div style={{
                  width: 28, height: 28,
                  borderRadius: "50%",
                  border: `1.5px solid ${accentColor}66`,
                  background: `${accentColor}11`,
                  display: "flex", alignItems: "center", justifyContent: "center",
                  color: accentColor,
                  fontSize: 12,
                  flexShrink: 0,
                  transition: "transform 0.2s",
                  transform: isOpen ? "rotate(180deg)" : "none",
                }}>▼</div>
              </button>

              {/* Products */}
              {isOpen && (
                <div style={{ borderTop: `1px solid ${accentColor}33` }}>
                  {Object.entries(fmtGroups).map(([fmt, items]) => (
                    <div key={fmt}>
                      {Object.keys(fmtGroups).length > 1 && (
                        <div style={{
                          padding: "6px 14px",
                          fontSize: 10,
                          letterSpacing: 2,
                          color: "#555",
                          background: "#0d0d14",
                          fontWeight: 700,
                        }}>
                          {FORMAT_ICONS[fmt]} {fmt.toUpperCase()}
                        </div>
                      )}
                      {items
                        .sort((a, b) => nutrient.startsWith("High") ? parsePct(b.pct) - parsePct(a.pct) : parsePct(a.pct) - parsePct(b.pct))
                        .map((item, idx) => (
                          <div key={idx} style={{
                            display: "flex",
                            alignItems: "center",
                            padding: "10px 14px",
                            borderTop: `1px solid #1a1a2e`,
                            gap: 10,
                          }}>
                            <div style={{
                              width: 3,
                              height: 28,
                              background: accentColor,
                              borderRadius: 2,
                              opacity: 0.6,
                              flexShrink: 0,
                            }} />
                            <div style={{ flex: 1 }}>
                              <div style={{ fontSize: 13, color: "#ccc", lineHeight: 1.3 }}>
                                {item.product}
                              </div>
                            </div>
                            <div style={{
                              fontSize: 13,
                              fontWeight: 700,
                              color: accentColor,
                              opacity: 0.8,
                              flexShrink: 0,
                            }}>
                              {item.pct}
                            </div>
                          </div>
                        ))}
                    </div>
                  ))}
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}